// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import {
  getCurrentUserProfile,
  updateCurrentUserProfile,
  updateFileContent,
  getAgentById,
  updateAgent,
  createAgent,
  deleteAgent,
  listStarredAgents,
  starAgent,
  unStarAgent,
  publishAgent,
  followUser,
  unfollowUser,
  navigationChat,
  creationChat,
  uploadToolFile,
  getFileInfosByIds,
  uploadKnowledgeFile,
  uploadAvatarFile,
  signup,
  refreshToken,
  logout,
  login,
  importAgent,
  forkAgent,
  verifyCode,
  verifyCaptcha,
  sendRegistrationCode,
  sendPhoneCode,
  sendForgetPasswordCode,
  resetPassword,
  changePassword,
  getCaptcha,
  listUsers,
  getUserStats,
  getRecentUserActions,
  getUserProfileByUsername,
  getUserProfile,
  getUserFollowing,
  getUserFollowers,
  getUserActions,
  uploadKnowledgeFile1,
  getImageFile,
  getFileContent,
  getUserAgents,
  getTrendingAgents,
  getAgentStarUsers,
  searchAgentByKeyWord,
  getAgentReleaseHistory,
  getPublicAgents,
  downloadAgentMarkdown,
  getAgentForkUsers,
  listForkedAgents,
  countForks,
  exportAgent,
  getAgentByUserNameAndAgentName,
  cleanCreationChatSession,
  deleteFile,
  deleteFiles,
  deleteAgentFile,
} from '../services.gen';
import type {
  UpdateCurrentUserProfileData,
  UpdateCurrentUserProfileError,
  UpdateCurrentUserProfileResponse,
  UpdateFileContentData,
  UpdateFileContentError,
  UpdateFileContentResponse,
  GetAgentByIdData,
  UpdateAgentData,
  UpdateAgentError,
  UpdateAgentResponse,
  CreateAgentData,
  CreateAgentError,
  CreateAgentResponse,
  DeleteAgentData,
  DeleteAgentError,
  DeleteAgentResponse,
  ListStarredAgentsData,
  StarAgentData,
  StarAgentError,
  StarAgentResponse,
  UnStarAgentData,
  UnStarAgentError,
  UnStarAgentResponse,
  PublishAgentData,
  PublishAgentError,
  PublishAgentResponse,
  FollowUserData,
  FollowUserError,
  FollowUserResponse,
  UnfollowUserData,
  UnfollowUserError,
  UnfollowUserResponse,
  NavigationChatData,
  NavigationChatError,
  NavigationChatResponse,
  CreationChatData,
  CreationChatError,
  CreationChatResponse,
  UploadToolFileData,
  UploadToolFileError,
  UploadToolFileResponse,
  GetFileInfosByIdsData,
  GetFileInfosByIdsError,
  GetFileInfosByIdsResponse,
  UploadKnowledgeFileData,
  UploadKnowledgeFileError,
  UploadKnowledgeFileResponse,
  UploadAvatarFileData,
  UploadAvatarFileError,
  UploadAvatarFileResponse,
  SignupData,
  SignupError,
  SignupResponse,
  RefreshTokenError,
  RefreshTokenResponse,
  LogoutError,
  LogoutResponse,
  LoginData,
  LoginError,
  LoginResponse,
  ImportAgentData,
  ImportAgentError,
  ImportAgentResponse,
  ForkAgentData,
  ForkAgentError,
  ForkAgentResponse,
  VerifyCodeData,
  VerifyCodeError,
  VerifyCodeResponse,
  VerifyCaptchaData,
  VerifyCaptchaError,
  VerifyCaptchaResponse,
  SendRegistrationCodeData,
  SendRegistrationCodeError,
  SendRegistrationCodeResponse,
  SendPhoneCodeData,
  SendPhoneCodeError,
  SendPhoneCodeResponse,
  SendForgetPasswordCodeData,
  SendForgetPasswordCodeError,
  SendForgetPasswordCodeResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse,
  ChangePasswordData,
  ChangePasswordError,
  ChangePasswordResponse,
  GetCaptchaError,
  GetCaptchaResponse,
  ListUsersData,
  GetUserStatsData,
  GetRecentUserActionsData,
  GetUserProfileByUsernameData,
  GetUserProfileData,
  GetUserFollowingData,
  GetUserFollowersData,
  GetUserActionsData,
  UploadKnowledgeFile1Data,
  GetImageFileData,
  GetFileContentData,
  GetUserAgentsData,
  GetTrendingAgentsData,
  GetAgentStarUsersData,
  SearchAgentByKeyWordData,
  GetAgentReleaseHistoryData,
  GetPublicAgentsData,
  DownloadAgentMarkdownData,
  GetAgentForkUsersData,
  ListForkedAgentsData,
  CountForksData,
  ExportAgentData,
  GetAgentByUserNameAndAgentNameData,
  CleanCreationChatSessionError,
  CleanCreationChatSessionResponse,
  DeleteFileData,
  DeleteFileError,
  DeleteFileResponse,
  DeleteFilesData,
  DeleteFilesError,
  DeleteFilesResponse,
  DeleteAgentFileData,
  DeleteAgentFileError,
  DeleteAgentFileResponse,
} from '../types.gen';

export const getCurrentUserProfileOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getCurrentUserProfile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getCurrentUserProfile',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const updateCurrentUserProfileOptions = (
  options: Options<UpdateCurrentUserProfileData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await updateCurrentUserProfile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'updateCurrentUserProfile',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const updateCurrentUserProfileMutation: UseMutationOptions<
  UpdateCurrentUserProfileResponse,
  UpdateCurrentUserProfileError,
  Options<UpdateCurrentUserProfileData>
> = {
  mutationFn: async (options) => {
    const { data } = await updateCurrentUserProfile({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const updateFileContentOptions = (
  options: Options<UpdateFileContentData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await updateFileContent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'updateFileContent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const updateFileContentMutation: UseMutationOptions<
  UpdateFileContentResponse,
  UpdateFileContentError,
  Options<UpdateFileContentData>
> = {
  mutationFn: async (options) => {
    const { data } = await updateFileContent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const getAgentByIdOptions = (options: Options<GetAgentByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getAgentById({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getAgentById',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const updateAgentOptions = (options: Options<UpdateAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await updateAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'updateAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const updateAgentMutation: UseMutationOptions<
  UpdateAgentResponse,
  UpdateAgentError,
  Options<UpdateAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await updateAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const createAgentOptions = (options: Options<CreateAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await createAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'createAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const createAgentMutation: UseMutationOptions<
  CreateAgentResponse,
  CreateAgentError,
  Options<CreateAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await createAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const deleteAgentOptions = (options: Options<DeleteAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await deleteAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'deleteAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const deleteAgentMutation: UseMutationOptions<
  DeleteAgentResponse,
  DeleteAgentError,
  Options<DeleteAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await deleteAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const listStarredAgentsOptions = (
  options: Options<ListStarredAgentsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await listStarredAgents({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'listStarredAgents',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const starAgentOptions = (options: Options<StarAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await starAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'starAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const starAgentMutation: UseMutationOptions<
  StarAgentResponse,
  StarAgentError,
  Options<StarAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await starAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const unStarAgentOptions = (options: Options<UnStarAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await unStarAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'unStarAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const unStarAgentMutation: UseMutationOptions<
  UnStarAgentResponse,
  UnStarAgentError,
  Options<UnStarAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await unStarAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const publishAgentOptions = (options: Options<PublishAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await publishAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'publishAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const publishAgentMutation: UseMutationOptions<
  PublishAgentResponse,
  PublishAgentError,
  Options<PublishAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await publishAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const followUserOptions = (options: Options<FollowUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await followUser({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'followUser',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const followUserMutation: UseMutationOptions<
  FollowUserResponse,
  FollowUserError,
  Options<FollowUserData>
> = {
  mutationFn: async (options) => {
    const { data } = await followUser({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const unfollowUserOptions = (options: Options<UnfollowUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await unfollowUser({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'unfollowUser',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const unfollowUserMutation: UseMutationOptions<
  UnfollowUserResponse,
  UnfollowUserError,
  Options<UnfollowUserData>
> = {
  mutationFn: async (options) => {
    const { data } = await unfollowUser({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const navigationChatOptions = (options: Options<NavigationChatData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await navigationChat({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'navigationChat',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const navigationChatMutation: UseMutationOptions<
  NavigationChatResponse,
  NavigationChatError,
  Options<NavigationChatData>
> = {
  mutationFn: async (options) => {
    const { data } = await navigationChat({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const creationChatOptions = (options: Options<CreationChatData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await creationChat({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'creationChat',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const creationChatMutation: UseMutationOptions<
  CreationChatResponse,
  CreationChatError,
  Options<CreationChatData>
> = {
  mutationFn: async (options) => {
    const { data } = await creationChat({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const uploadToolFileOptions = (
  options?: Options<UploadToolFileData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await uploadToolFile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'uploadToolFile',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const uploadToolFileMutation: UseMutationOptions<
  UploadToolFileResponse,
  UploadToolFileError,
  Options<UploadToolFileData>
> = {
  mutationFn: async (options) => {
    const { data } = await uploadToolFile({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const getFileInfosByIdsOptions = (
  options: Options<GetFileInfosByIdsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getFileInfosByIds({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getFileInfosByIds',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getFileInfosByIdsMutation: UseMutationOptions<
  GetFileInfosByIdsResponse,
  GetFileInfosByIdsError,
  Options<GetFileInfosByIdsData>
> = {
  mutationFn: async (options) => {
    const { data } = await getFileInfosByIds({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const uploadKnowledgeFileOptions = (
  options?: Options<UploadKnowledgeFileData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await uploadKnowledgeFile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'uploadKnowledgeFile',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const uploadKnowledgeFileMutation: UseMutationOptions<
  UploadKnowledgeFileResponse,
  UploadKnowledgeFileError,
  Options<UploadKnowledgeFileData>
> = {
  mutationFn: async (options) => {
    const { data } = await uploadKnowledgeFile({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const uploadAvatarFileOptions = (
  options?: Options<UploadAvatarFileData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await uploadAvatarFile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'uploadAvatarFile',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const uploadAvatarFileMutation: UseMutationOptions<
  UploadAvatarFileResponse,
  UploadAvatarFileError,
  Options<UploadAvatarFileData>
> = {
  mutationFn: async (options) => {
    const { data } = await uploadAvatarFile({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const signupOptions = (options: Options<SignupData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await signup({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'signup',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const signupMutation: UseMutationOptions<
  SignupResponse,
  SignupError,
  Options<SignupData>
> = {
  mutationFn: async (options) => {
    const { data } = await signup({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const refreshTokenOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await refreshToken({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'refreshToken',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const refreshTokenMutation: UseMutationOptions<
  RefreshTokenResponse,
  RefreshTokenError,
  Options
> = {
  mutationFn: async (options) => {
    const { data } = await refreshToken({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const logoutOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await logout({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'logout',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const logoutMutation: UseMutationOptions<
  LogoutResponse,
  LogoutError,
  Options
> = {
  mutationFn: async (options) => {
    const { data } = await logout({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const loginOptions = (options: Options<LoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await login({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'login',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const loginMutation: UseMutationOptions<
  LoginResponse,
  LoginError,
  Options<LoginData>
> = {
  mutationFn: async (options) => {
    const { data } = await login({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const importAgentOptions = (options?: Options<ImportAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await importAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'importAgent',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const importAgentMutation: UseMutationOptions<
  ImportAgentResponse,
  ImportAgentError,
  Options<ImportAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await importAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const forkAgentOptions = (options: Options<ForkAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await forkAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'forkAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const forkAgentMutation: UseMutationOptions<
  ForkAgentResponse,
  ForkAgentError,
  Options<ForkAgentData>
> = {
  mutationFn: async (options) => {
    const { data } = await forkAgent({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const verifyCodeOptions = (options: Options<VerifyCodeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await verifyCode({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'verifyCode',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const verifyCodeMutation: UseMutationOptions<
  VerifyCodeResponse,
  VerifyCodeError,
  Options<VerifyCodeData>
> = {
  mutationFn: async (options) => {
    const { data } = await verifyCode({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const verifyCaptchaOptions = (options: Options<VerifyCaptchaData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await verifyCaptcha({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'verifyCaptcha',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const verifyCaptchaMutation: UseMutationOptions<
  VerifyCaptchaResponse,
  VerifyCaptchaError,
  Options<VerifyCaptchaData>
> = {
  mutationFn: async (options) => {
    const { data } = await verifyCaptcha({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const sendRegistrationCodeOptions = (
  options: Options<SendRegistrationCodeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await sendRegistrationCode({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'sendRegistrationCode',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const sendRegistrationCodeMutation: UseMutationOptions<
  SendRegistrationCodeResponse,
  SendRegistrationCodeError,
  Options<SendRegistrationCodeData>
> = {
  mutationFn: async (options) => {
    const { data } = await sendRegistrationCode({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const sendPhoneCodeOptions = (options: Options<SendPhoneCodeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await sendPhoneCode({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'sendPhoneCode',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const sendPhoneCodeMutation: UseMutationOptions<
  SendPhoneCodeResponse,
  SendPhoneCodeError,
  Options<SendPhoneCodeData>
> = {
  mutationFn: async (options) => {
    const { data } = await sendPhoneCode({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const sendForgetPasswordCodeOptions = (
  options: Options<SendForgetPasswordCodeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await sendForgetPasswordCode({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'sendForgetPasswordCode',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const sendForgetPasswordCodeMutation: UseMutationOptions<
  SendForgetPasswordCodeResponse,
  SendForgetPasswordCodeError,
  Options<SendForgetPasswordCodeData>
> = {
  mutationFn: async (options) => {
    const { data } = await sendForgetPasswordCode({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const resetPasswordOptions = (options: Options<ResetPasswordData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await resetPassword({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'resetPassword',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const resetPasswordMutation: UseMutationOptions<
  ResetPasswordResponse,
  ResetPasswordError,
  Options<ResetPasswordData>
> = {
  mutationFn: async (options) => {
    const { data } = await resetPassword({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const changePasswordOptions = (options: Options<ChangePasswordData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await changePassword({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'changePassword',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const changePasswordMutation: UseMutationOptions<
  ChangePasswordResponse,
  ChangePasswordError,
  Options<ChangePasswordData>
> = {
  mutationFn: async (options) => {
    const { data } = await changePassword({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const getCaptchaOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getCaptcha({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getCaptcha',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const getCaptchaMutation: UseMutationOptions<
  GetCaptchaResponse,
  GetCaptchaError,
  Options
> = {
  mutationFn: async (options) => {
    const { data } = await getCaptcha({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const listUsersOptions = (options?: Options<ListUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'listUsers',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const getUserStatsOptions = (options: Options<GetUserStatsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserStats({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserStats',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getRecentUserActionsOptions = (
  options: Options<GetRecentUserActionsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getRecentUserActions({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getRecentUserActions',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getUserProfileByUsernameOptions = (
  options: Options<GetUserProfileByUsernameData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserProfileByUsername({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserProfileByUsername',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getUserProfileOptions = (options: Options<GetUserProfileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserProfile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserProfile',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getUserFollowingOptions = (
  options: Options<GetUserFollowingData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserFollowing({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserFollowing',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getUserFollowersOptions = (
  options: Options<GetUserFollowersData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserFollowers({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserFollowers',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getUserActionsOptions = (options: Options<GetUserActionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserActions({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserActions',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const uploadKnowledgeFile1Options = (
  options: Options<UploadKnowledgeFile1Data>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await uploadKnowledgeFile1({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'uploadKnowledgeFile1',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getImageFileOptions = (options: Options<GetImageFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getImageFile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getImageFile',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getFileContentOptions = (options: Options<GetFileContentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getFileContent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getFileContent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getUserAgentsOptions = (options: Options<GetUserAgentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getUserAgents({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getUserAgents',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getTrendingAgentsOptions = (
  options: Options<GetTrendingAgentsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getTrendingAgents({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getTrendingAgents',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getAgentStarUsersOptions = (
  options: Options<GetAgentStarUsersData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getAgentStarUsers({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getAgentStarUsers',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const searchAgentByKeyWordOptions = (
  options: Options<SearchAgentByKeyWordData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await searchAgentByKeyWord({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'searchAgentByKeyWord',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getAgentReleaseHistoryOptions = (
  options: Options<GetAgentReleaseHistoryData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getAgentReleaseHistory({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getAgentReleaseHistory',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getPublicAgentsOptions = (
  options: Options<GetPublicAgentsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getPublicAgents({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getPublicAgents',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const downloadAgentMarkdownOptions = (
  options: Options<DownloadAgentMarkdownData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await downloadAgentMarkdown({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'downloadAgentMarkdown',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getAgentForkUsersOptions = (
  options: Options<GetAgentForkUsersData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getAgentForkUsers({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getAgentForkUsers',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const listForkedAgentsOptions = (
  options: Options<ListForkedAgentsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await listForkedAgents({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'listForkedAgents',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const countForksOptions = (options: Options<CountForksData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await countForks({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'countForks',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const exportAgentOptions = (options: Options<ExportAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await exportAgent({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'exportAgent',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const getAgentByUserNameAndAgentNameOptions = (
  options: Options<GetAgentByUserNameAndAgentNameData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await getAgentByUserNameAndAgentName({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'getAgentByUserNameAndAgentName',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const cleanCreationChatSessionOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await cleanCreationChatSession({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'cleanCreationChatSession',
        params: {
          body: options?.body,
          headers: options?.headers,
          path: options?.path,
          query: options?.query,
        },
      },
    ],
  });
};

export const cleanCreationChatSessionMutation: UseMutationOptions<
  CleanCreationChatSessionResponse,
  CleanCreationChatSessionError,
  Options
> = {
  mutationFn: async (options) => {
    const { data } = await cleanCreationChatSession({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const deleteFileOptions = (options: Options<DeleteFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await deleteFile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'deleteFile',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const deleteFileMutation: UseMutationOptions<
  DeleteFileResponse,
  DeleteFileError,
  Options<DeleteFileData>
> = {
  mutationFn: async (options) => {
    const { data } = await deleteFile({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const deleteFilesOptions = (options: Options<DeleteFilesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await deleteFiles({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'deleteFiles',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const deleteFilesMutation: UseMutationOptions<
  DeleteFilesResponse,
  DeleteFilesError,
  Options<DeleteFilesData>
> = {
  mutationFn: async (options) => {
    const { data } = await deleteFiles({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};

export const deleteAgentFileOptions = (
  options: Options<DeleteAgentFileData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey }) => {
      const { data } = await deleteAgentFile({
        ...options,
        ...queryKey[0].params,
        throwOnError: true,
      });
      return data;
    },
    queryKey: [
      {
        scope: 'deleteAgentFile',
        params: {
          body: options.body,
          headers: options.headers,
          path: options.path,
          query: options.query,
        },
      },
    ],
  });
};

export const deleteAgentFileMutation: UseMutationOptions<
  DeleteAgentFileResponse,
  DeleteAgentFileError,
  Options<DeleteAgentFileData>
> = {
  mutationFn: async (options) => {
    const { data } = await deleteAgentFile({
      ...options,
      throwOnError: true,
    });
    return data;
  },
};
