// This file is auto-generated by @hey-api/openapi-ts

export const $RVoid = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {},
  },
} as const;

export const $UpdateUserDTO = {
  type: 'object',
  description: '更新用户信息DTO',
  properties: {
    id: {
      type: 'string',
      description: '用户唯一标识',
    },
    email: {
      type: 'string',
      description: '用户邮箱',
    },
    nickName: {
      type: 'string',
      description: '昵称',
    },
    avatar: {
      type: 'string',
      description: '用户头像URL',
    },
    bio: {
      type: 'string',
      description: '用户简介',
    },
    location: {
      type: 'string',
      description: '用户位置',
    },
    website: {
      type: 'string',
      description: '用户网站',
    },
  },
  required: ['id'],
} as const;

export const $RBoolean = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      type: 'boolean',
    },
  },
} as const;

export const $UpdateFileContentDTO = {
  type: 'object',
  description: '更新文件内容',
  properties: {
    id: {
      type: 'string',
      description: '文件ID',
      minLength: 1,
    },
    content: {
      type: 'string',
      description: '文件内容',
      minLength: 1,
    },
  },
  required: ['content', 'id'],
} as const;

export const $AgentLicenseDTO = {
  type: 'object',
  description: 'AgentLicense信息DTO',
  properties: {
    id: {
      type: 'string',
      description: 'License唯一标识,创建时不需要传，修改时必传',
    },
    agentId: {
      type: 'string',
      description: 'Agent唯一标识',
    },
    type: {
      type: 'string',
      description: '协议类型',
      enum: [
        'MIT',
        'APACHE_2_0',
        'GPL_3_0',
        'BSD_3_CLAUSE',
        'AGPL_3_0',
        'PROPRIETARY',
        'CUSTOM',
      ],
    },
    url: {
      type: 'string',
      description: '官方协议或自定义协议链接',
    },
    text: {
      type: 'string',
      description: '若为自定义协议，可直接存放文本',
    },
    allowFork: {
      type: 'boolean',
      description: '是否允许 Fork，前端显示或限制逻辑可用',
    },
    createTime: {
      type: 'string',
      format: 'date-time',
      description: '创建时间',
    },
    updateTime: {
      type: 'string',
      format: 'date-time',
      description: '更新时间',
    },
  },
} as const;

export const $UpdateAgentDTO = {
  type: 'object',
  description: 'Agent更新信息DTO',
  properties: {
    id: {
      type: 'string',
      description: 'Agent唯一标识',
    },
    name: {
      type: 'string',
      description: 'Agent名称',
    },
    description: {
      type: 'string',
      description: 'Agent描述',
    },
    platform: {
      type: 'string',
      description: '平台类型 (LiteAgent、Dify、Coze等)',
      enum: ['LiteAgent', 'Dify', 'Coze'],
    },
    mdContent: {
      type: 'string',
      description: 'md内容',
    },
    toolFileIdList: {
      type: 'array',
      description: '工具文件id列表',
      items: {
        type: 'string',
      },
    },
    docsFileIdList: {
      type: 'array',
      description: '知识库md文档id列表',
      items: {
        type: 'string',
      },
    },
    category: {
      type: 'string',
      description: '分类',
    },
    isPublic: {
      type: 'boolean',
      description: '是否公开',
    },
    tags: {
      type: 'array',
      description: '标签列表',
      items: {
        type: 'string',
      },
    },
    license: {
      $ref: '#/components/schemas/AgentLicenseDTO',
      description: 'license信息',
    },
  },
  required: ['mdContent', 'name', 'platform'],
} as const;

export const $RObject = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {},
  },
} as const;

export const $PublishAgentDTO = {
  type: 'object',
  description: '发布Agent信息DTO',
  properties: {
    id: {
      type: 'string',
      description: 'Agent ID',
      minLength: 1,
    },
    version: {
      type: 'string',
      description: '版本号',
    },
    releaseNotes: {
      type: 'string',
      description: '发布说明',
    },
  },
  required: ['id', 'version'],
} as const;

export const $AgentChatDTO = {
  type: 'object',
  description: 'agent 聊天DTO',
  properties: {
    content: {
      type: 'string',
      description: '聊天内容',
    },
  },
} as const;

export const $AgentDTO = {
  type: 'object',
  description: 'Agent信息DTO',
  properties: {
    id: {
      type: 'string',
      description: 'Agent唯一标识',
    },
    name: {
      type: 'string',
      description: 'Agent名称',
    },
    description: {
      type: 'string',
      description: 'Agent描述',
    },
    platform: {
      type: 'string',
      description: '平台类型 (LiteAgent、Dify、Coze等)',
      enum: ['LiteAgent', 'Dify', 'Coze'],
    },
    mdContent: {
      type: 'string',
      description: 'md内容',
    },
    toolFileIdList: {
      type: 'array',
      description: '工具文件id列表',
      items: {
        type: 'string',
      },
    },
    docsFileIdList: {
      type: 'array',
      description: '知识库md文档id列表',
      items: {
        type: 'string',
      },
    },
    documentId: {
      type: 'string',
      description: '摘要文档id',
    },
    authorId: {
      type: 'string',
      description: '作者用户ID',
    },
    authorName: {
      type: 'string',
      description: '作者用户名',
    },
    authorNickName: {
      type: 'string',
      description: '作者昵称',
    },
    category: {
      type: 'string',
      description: '分类',
    },
    isPublic: {
      type: 'boolean',
      description: '是否公开',
    },
    tags: {
      type: 'array',
      description: '标签列表',
      items: {
        type: 'string',
      },
    },
    version: {
      type: 'string',
      description: '版本号',
    },
    stars: {
      type: 'integer',
      format: 'int32',
      description: '收藏数',
    },
    forks: {
      type: 'integer',
      format: 'int32',
      description: '分叉数',
    },
    views: {
      type: 'integer',
      format: 'int32',
      description: '浏览数',
    },
    isPublished: {
      type: 'boolean',
      description: '是否发布',
    },
    createTime: {
      type: 'string',
      format: 'date-time',
      description: '创建时间',
    },
    updateTime: {
      type: 'string',
      format: 'date-time',
      description: '更新时间',
    },
    isStarred: {
      type: 'boolean',
      description: '是否已star',
    },
    forkInfo: {
      $ref: '#/components/schemas/ForkDTO',
      description: 'fork 信息',
    },
    license: {
      $ref: '#/components/schemas/AgentLicenseDTO',
      description: 'license信息',
    },
  },
  required: ['mdContent', 'name', 'platform'],
} as const;

export const $ForkDTO = {
  type: 'object',
  description: 'Fork信息DTO',
  properties: {
    id: {
      type: 'string',
      description: 'Fork记录唯一标识',
    },
    userId: {
      type: 'string',
      description: 'Fork用户ID',
    },
    originalAgentId: {
      type: 'string',
      description: '原始Agent ID',
    },
    forkedAgentId: {
      type: 'string',
      description: 'Fork后的新Agent ID',
    },
    originalAgentName: {
      type: 'string',
      description: '原始Agent名称',
    },
    originalAgentAuthorId: {
      type: 'string',
      description: '原始Agent 作者id',
    },
    originalAgentAuthorName: {
      type: 'string',
      description: '原始Agent 作者名称',
    },
    originalAgentAuthorNickName: {
      type: 'string',
      description: '原始Agent 作者昵称',
    },
    createTime: {
      type: 'string',
      format: 'date-time',
      description: '创建时间',
    },
  },
} as const;

export const $NavigationResultDTO = {
  type: 'object',
  description: '导航结果DTO',
  properties: {
    text: {
      type: 'string',
      description: '导航结果',
    },
    type: {
      type: 'string',
      description: '导航结果类型',
    },
    agentDTOS: {
      type: 'array',
      description: '搜索结果',
      items: {
        $ref: '#/components/schemas/AgentDTO',
      },
    },
  },
} as const;

export const $RNavigationResultDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/NavigationResultDTO',
    },
  },
} as const;

export const $CreationChatDTO = {
  type: 'object',
  description: 'agent创作编辑接口DTO',
  properties: {
    cmd: {
      type: 'string',
      description: '用户指令',
      minLength: 1,
    },
    toolFileIdList: {
      type: 'array',
      description: '工具文件id列表',
      items: {
        type: 'string',
      },
    },
    docsFileIdList: {
      type: 'array',
      description: '知识库md文档id列表',
      items: {
        type: 'string',
      },
    },
  },
  required: ['cmd'],
} as const;

export const $ServerSentEventAgentMessage = {} as const;

export const $FileDocMetadataDTO = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    separator: {
      type: 'string',
    },
  },
} as const;

export const $FileInfoDTO = {
  type: 'object',
  description: '文件信息DTO',
  properties: {
    id: {
      type: 'string',
      description: '文件ID',
    },
    fileName: {
      type: 'string',
      description: '完整文件名',
    },
    fileSize: {
      type: 'integer',
      format: 'int64',
      description: '文件大小 (字节)',
    },
    fileType: {
      type: 'string',
      description: '文件类型',
    },
    type: {
      type: 'string',
      description: '上传类型',
      enum: ['TOOLS', 'AVATARS', 'KNOWLEDGE'],
    },
    md5: {
      type: 'string',
      description: 'md5',
    },
    metadata: {
      $ref: '#/components/schemas/FileDocMetadataDTO',
      description:
        '文档文件的元数据 从liteagent导入的需保留原数据，否则导出时生成',
    },
    imagesFileIds: {
      type: 'array',
      description: '关联图片文件ID',
      items: {
        type: 'string',
      },
    },
    userId: {
      type: 'string',
      description: '上传用户ID',
    },
    uploadTime: {
      type: 'string',
      format: 'date-time',
      description: '上传时间',
    },
  },
} as const;

export const $RFileInfoDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/FileInfoDTO',
    },
  },
} as const;

export const $RListFileInfoDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/FileInfoDTO',
      },
    },
  },
} as const;

export const $RString = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      type: 'string',
    },
  },
} as const;

export const $SignupRequestDTO = {
  type: 'object',
  description: '注册请求DTO',
  properties: {
    userName: {
      type: 'string',
      description: '用户名',
      example: 'john-doe',
    },
    email: {
      type: 'string',
      description: '邮箱地址',
      example: 'user@example.com',
      minLength: 1,
    },
    phone: {
      type: 'string',
      description: '手机号',
    },
    avatar: {
      type: 'string',
      description: '头像地址',
    },
    password: {
      type: 'string',
      description: '密码',
      example: 'Password123!',
    },
  },
  required: ['email'],
} as const;

export const $RUserDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/UserDTO',
    },
  },
} as const;

export const $UserDTO = {
  type: 'object',
  description: '用户信息DTO',
  properties: {
    id: {
      type: 'string',
      description: '用户唯一标识',
    },
    email: {
      type: 'string',
      description: '用户邮箱',
    },
    userName: {
      type: 'string',
      description: '用户名',
    },
    nickName: {
      type: 'string',
      description: '昵称',
    },
    avatar: {
      type: 'string',
      description: '用户头像URL',
    },
    bio: {
      type: 'string',
      description: '用户简介',
    },
    location: {
      type: 'string',
      description: '用户位置',
    },
    website: {
      type: 'string',
      description: '用户网站',
    },
    role: {
      type: 'string',
      description: '用户角色',
      enum: ['ROLE_USER', 'ROLE_ADMIN'],
    },
    status: {
      type: 'string',
      description: '用户状态',
      enum: ['NORMAL', 'LOCKED', 'DELETED'],
    },
    following: {
      type: 'boolean',
      description: '是否被当前用户关注',
    },
    createTime: {
      type: 'string',
      format: 'date-time',
      description: '创建时间',
    },
    updateTime: {
      type: 'string',
      format: 'date-time',
      description: '更新时间',
    },
    lastLoginTime: {
      type: 'string',
      format: 'date-time',
      description: '最后登录时间',
    },
  },
  required: ['id'],
} as const;

export const $LoginRequestDTO = {
  type: 'object',
  description: '登录请求DTO',
  properties: {
    email: {
      type: 'string',
      description: '邮箱地址',
      example: 'user@example.com',
    },
    password: {
      type: 'string',
      description: '密码',
      example: 'password123',
      minLength: 1,
    },
  },
  required: ['password'],
} as const;

export const $RSaTokenInfo = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/SaTokenInfo',
    },
  },
} as const;

export const $SaTokenInfo = {
  type: 'object',
  properties: {
    tokenName: {
      type: 'string',
    },
    tokenValue: {
      type: 'string',
    },
    isLogin: {
      type: 'boolean',
    },
    loginId: {},
    loginType: {
      type: 'string',
    },
    tokenTimeout: {
      type: 'integer',
      format: 'int64',
    },
    sessionTimeout: {
      type: 'integer',
      format: 'int64',
    },
    tokenSessionTimeout: {
      type: 'integer',
      format: 'int64',
    },
    tokenActiveTimeout: {
      type: 'integer',
      format: 'int64',
    },
    loginDeviceType: {
      type: 'string',
    },
    tag: {
      type: 'string',
    },
  },
} as const;

export const $CreateAgentDTO = {
  type: 'object',
  description: '创建Agent信息DTO',
  properties: {
    id: {
      type: 'string',
      description: 'AgentId',
    },
    name: {
      type: 'string',
      description: 'Agent名称',
    },
    description: {
      type: 'string',
      description: 'Agent描述',
    },
    platform: {
      type: 'string',
      description: '平台类型 (LiteAgent、Dify、Coze等)',
      enum: ['LiteAgent', 'Dify', 'Coze'],
    },
    mdContent: {
      type: 'string',
      description: 'md内容',
    },
    toolFileIdList: {
      type: 'array',
      description: '工具文件id列表',
      items: {
        type: 'string',
      },
    },
    docsFileIdList: {
      type: 'array',
      description: '知识库md文档id列表',
      items: {
        type: 'string',
      },
    },
    license: {
      $ref: '#/components/schemas/AgentLicenseDTO',
      description: 'license信息',
    },
    isPublic: {
      type: 'boolean',
      description: '是否公开',
    },
  },
  required: ['mdContent', 'name', 'platform'],
} as const;

export const $RAgentDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/AgentDTO',
    },
  },
} as const;

export const $ForkRequestDTO = {
  type: 'object',
  description: 'Agent Fork请求DTO',
  properties: {
    name: {
      type: 'string',
      description:
        'Fork后的Agent名称（可选，如果不提供则使用原名称 + " (Fork)"）',
    },
    description: {
      type: 'string',
      description: 'Fork后的Agent描述（可选，如果不提供则使用原描述）',
    },
  },
} as const;

export const $VerifyCodeDTO = {
  type: 'object',
  description: '验证码验证请求DTO',
  properties: {
    email: {
      type: 'string',
      description: '邮箱地址',
      example: 'user@example.com',
    },
    phone: {
      type: 'string',
      description: '手机号',
    },
    code: {
      type: 'string',
      description: '验证码',
      example: 123456,
      minLength: 1,
    },
  },
  required: ['code'],
} as const;

export const $CaptchaDTO = {
  type: 'object',
  description: '图片验证码DTO',
  properties: {
    captchaKey: {
      type: 'string',
      description: '验证码key',
      minLength: 1,
    },
    captchaCode: {
      type: 'string',
      description: '用户输入的验证码',
      minLength: 1,
    },
  },
  required: ['captchaCode', 'captchaKey'],
} as const;

export const $SendVerifyCodeDTO = {
  type: 'object',
  description: '发送验证码DTO',
  properties: {
    email: {
      type: 'string',
      description: '邮箱地址',
      example: 'user@example.com',
    },
    phone: {
      type: 'string',
      description: '手机号',
    },
  },
} as const;

export const $ResetPasswordDTO = {
  type: 'object',
  description: '重置密码请求DTO',
  properties: {
    email: {
      type: 'string',
      description: '邮箱地址',
      example: 'user@example.com',
      minLength: 1,
    },
    newPassword: {
      type: 'string',
      description: '新密码',
      example: 'newPassword123',
      minLength: 1,
    },
  },
  required: ['email', 'newPassword'],
} as const;

export const $ChangePasswordDTO = {
  type: 'object',
  description: '修改密码请求DTO',
  properties: {
    currentPassword: {
      type: 'string',
      description: '当前密码',
      minLength: 1,
    },
    newPassword: {
      type: 'string',
      description: '新密码',
    },
  },
  required: ['currentPassword'],
} as const;

export const $PageResultUserDTO = {
  type: 'object',
  properties: {
    pageNum: {
      type: 'integer',
      format: 'int64',
    },
    pageSize: {
      type: 'integer',
      format: 'int64',
    },
    totalSize: {
      type: 'integer',
      format: 'int64',
    },
    totalPages: {
      type: 'integer',
      format: 'int64',
    },
    contentData: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/UserDTO',
      },
    },
    hasPreviousPage: {
      type: 'boolean',
    },
    hasNextPage: {
      type: 'boolean',
    },
    firstPage: {
      type: 'boolean',
    },
    lastPage: {
      type: 'boolean',
    },
  },
} as const;

export const $RPageResultUserDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/PageResultUserDTO',
    },
  },
} as const;

export const $RUserStatsDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/UserStatsDTO',
    },
  },
} as const;

export const $UserStatsDTO = {
  type: 'object',
  description: '用户统计数据DTO',
  properties: {
    userId: {
      type: 'string',
      description: '用户ID',
    },
    followingCount: {
      type: 'integer',
      format: 'int64',
      description: '关注数',
    },
    followerCount: {
      type: 'integer',
      format: 'int64',
      description: '粉丝数',
    },
    starCount: {
      type: 'integer',
      format: 'int64',
      description: '收藏数',
    },
    forkCount: {
      type: 'integer',
      format: 'int64',
      description: '分叉数',
    },
    agentCount: {
      type: 'integer',
      format: 'int64',
      description: '创建的Agent数',
    },
    totalViews: {
      type: 'integer',
      format: 'int64',
      description: '总浏览数',
    },
  },
} as const;

export const $RListUserActionLogDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/UserActionLogDTO',
      },
    },
  },
} as const;

export const $UserActionLogDTO = {
  type: 'object',
  description: '操作日志DTO',
  properties: {
    id: {
      type: 'string',
      description: '日志唯一标识',
    },
    userId: {
      type: 'string',
      description: '用户ID',
    },
    userName: {
      type: 'string',
      description: '用户名称',
    },
    nickName: {
      type: 'string',
      description: '用户昵称',
    },
    actionType: {
      type: 'string',
      description: '操作类型',
      enum: [
        'STAR_AGENT',
        'UNSTAR_AGENT',
        'FOLLOW_USER',
        'UNFOLLOW_USER',
        'EDIT_AGENT',
        'FORK_AGENT',
        'CREATE_AGENT',
        'DELETE_AGENT',
        'PUBLISH_AGENT',
      ],
    },
    targetAgentId: {
      type: 'string',
      description: '操作目标 agent ID ',
    },
    targetAgentName: {
      type: 'string',
      description: '操作目标 agent 名称 ',
    },
    targetUserId: {
      type: 'string',
      description: '操作目标 用户 ID ',
    },
    targetUserName: {
      type: 'string',
      description: '操作目标 用户名称 ',
    },
    targetUserNickName: {
      type: 'string',
      description: '操作目标 用户昵称 ',
    },
    description: {
      type: 'string',
      description: '操作描述',
    },
    actionTime: {
      type: 'string',
      format: 'date-time',
      description: '操作时间',
    },
  },
} as const;

export const $PageResultUserActionLogDTO = {
  type: 'object',
  properties: {
    pageNum: {
      type: 'integer',
      format: 'int64',
    },
    pageSize: {
      type: 'integer',
      format: 'int64',
    },
    totalSize: {
      type: 'integer',
      format: 'int64',
    },
    totalPages: {
      type: 'integer',
      format: 'int64',
    },
    contentData: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/UserActionLogDTO',
      },
    },
    hasPreviousPage: {
      type: 'boolean',
    },
    hasNextPage: {
      type: 'boolean',
    },
    firstPage: {
      type: 'boolean',
    },
    lastPage: {
      type: 'boolean',
    },
  },
} as const;

export const $RPageResultUserActionLogDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/PageResultUserActionLogDTO',
    },
  },
} as const;

export const $ConversionProgressDTO = {
  type: 'object',
  properties: {
    progress: {
      type: 'number',
      format: 'double',
      description: '进度',
    },
    stage: {
      type: 'string',
      description: '状态',
    },
    detail: {
      type: 'string',
      description: '详情',
    },
    fileInfoDTO: {
      $ref: '#/components/schemas/FileInfoDTO',
      description: '文件信息,完成时返回',
    },
  },
} as const;

export const $RConversionProgressDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/ConversionProgressDTO',
    },
  },
} as const;

export const $PageResultAgentDTO = {
  type: 'object',
  properties: {
    pageNum: {
      type: 'integer',
      format: 'int64',
    },
    pageSize: {
      type: 'integer',
      format: 'int64',
    },
    totalSize: {
      type: 'integer',
      format: 'int64',
    },
    totalPages: {
      type: 'integer',
      format: 'int64',
    },
    contentData: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/AgentDTO',
      },
    },
    hasPreviousPage: {
      type: 'boolean',
    },
    hasNextPage: {
      type: 'boolean',
    },
    firstPage: {
      type: 'boolean',
    },
    lastPage: {
      type: 'boolean',
    },
  },
} as const;

export const $RPageResultAgentDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/PageResultAgentDTO',
    },
  },
} as const;

export const $RListAgentDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/AgentDTO',
      },
    },
  },
} as const;

export const $AgentReleaseDTO = {
  type: 'object',
  description: 'Agent发布历史记录DTO',
  properties: {
    id: {
      type: 'string',
      description: '发布信息唯一标识',
    },
    agentId: {
      type: 'string',
      description: 'Agent ID',
    },
    version: {
      type: 'string',
      description: '版本号',
    },
    releaseNotes: {
      type: 'string',
      description: '发布说明',
    },
    createTime: {
      type: 'string',
      format: 'date-time',
      description: '创建时间',
    },
  },
} as const;

export const $PageResultAgentReleaseDTO = {
  type: 'object',
  properties: {
    pageNum: {
      type: 'integer',
      format: 'int64',
    },
    pageSize: {
      type: 'integer',
      format: 'int64',
    },
    totalSize: {
      type: 'integer',
      format: 'int64',
    },
    totalPages: {
      type: 'integer',
      format: 'int64',
    },
    contentData: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/AgentReleaseDTO',
      },
    },
    hasPreviousPage: {
      type: 'boolean',
    },
    hasNextPage: {
      type: 'boolean',
    },
    firstPage: {
      type: 'boolean',
    },
    lastPage: {
      type: 'boolean',
    },
  },
} as const;

export const $RPageResultAgentReleaseDTO = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      $ref: '#/components/schemas/PageResultAgentReleaseDTO',
    },
  },
} as const;

export const $RInteger = {
  type: 'object',
  properties: {
    code: {
      type: 'integer',
      format: 'int32',
    },
    msg: {
      type: 'string',
    },
    data: {
      type: 'integer',
      format: 'int32',
    },
  },
} as const;
