// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from '@hey-api/client-fetch';
import {
  type GetCurrentUserProfileError,
  type GetCurrentUserProfileResponse,
  type UpdateCurrentUserProfileData,
  type UpdateCurrentUserProfileError,
  type UpdateCurrentUserProfileResponse,
  type UpdateFileContentData,
  type UpdateFileContentError,
  type UpdateFileContentResponse,
  type GetAgentByIdData,
  type GetAgentByIdError,
  type GetAgentByIdResponse,
  type UpdateAgentData,
  type UpdateAgentError,
  type UpdateAgentResponse,
  type CreateAgentData,
  type CreateAgentError,
  type CreateAgentResponse,
  type DeleteAgentData,
  type DeleteAgentError,
  type DeleteAgentResponse,
  type ListStarredAgentsData,
  type ListStarredAgentsError,
  type ListStarredAgentsResponse,
  type StarAgentData,
  type StarAgentError,
  type StarAgentResponse,
  type UnStarAgentData,
  type UnStarAgentError,
  type UnStarAgentResponse,
  type PublishAgentData,
  type PublishAgentError,
  type PublishAgentResponse,
  type FollowUserData,
  type FollowUserError,
  type FollowUserResponse,
  type UnfollowUserData,
  type UnfollowUserError,
  type UnfollowUserResponse,
  type NavigationChatData,
  type NavigationChatError,
  type NavigationChatResponse,
  type CreationChatData,
  type CreationChatError,
  type CreationChatResponse,
  type UploadToolFileData,
  type UploadToolFileError,
  type UploadToolFileResponse,
  type GetFileInfosByIdsData,
  type GetFileInfosByIdsError,
  type GetFileInfosByIdsResponse,
  type UploadKnowledgeFileData,
  type UploadKnowledgeFileError,
  type UploadKnowledgeFileResponse,
  type UploadAvatarFileData,
  type UploadAvatarFileError,
  type UploadAvatarFileResponse,
  type SignupData,
  type SignupError,
  type SignupResponse,
  type RefreshTokenError,
  type RefreshTokenResponse,
  type LogoutError,
  type LogoutResponse,
  type LoginData,
  type LoginError,
  type LoginResponse,
  type ImportAgentData,
  type ImportAgentError,
  type ImportAgentResponse,
  type ForkAgentData,
  type ForkAgentError,
  type ForkAgentResponse,
  type VerifyCodeData,
  type VerifyCodeError,
  type VerifyCodeResponse,
  type VerifyCaptchaData,
  type VerifyCaptchaError,
  type VerifyCaptchaResponse,
  type SendRegistrationCodeData,
  type SendRegistrationCodeError,
  type SendRegistrationCodeResponse,
  type SendPhoneCodeData,
  type SendPhoneCodeError,
  type SendPhoneCodeResponse,
  type SendForgetPasswordCodeData,
  type SendForgetPasswordCodeError,
  type SendForgetPasswordCodeResponse,
  type ResetPasswordData,
  type ResetPasswordError,
  type ResetPasswordResponse,
  type ChangePasswordData,
  type ChangePasswordError,
  type ChangePasswordResponse,
  type GetCaptchaError,
  type GetCaptchaResponse,
  type ListUsersData,
  type ListUsersError,
  type ListUsersResponse,
  type GetUserStatsData,
  type GetUserStatsError,
  type GetUserStatsResponse,
  type GetRecentUserActionsData,
  type GetRecentUserActionsError,
  type GetRecentUserActionsResponse,
  type GetUserProfileByUsernameData,
  type GetUserProfileByUsernameError,
  type GetUserProfileByUsernameResponse,
  type GetUserProfileData,
  type GetUserProfileError,
  type GetUserProfileResponse,
  type GetUserFollowingData,
  type GetUserFollowingError,
  type GetUserFollowingResponse,
  type GetUserFollowersData,
  type GetUserFollowersError,
  type GetUserFollowersResponse,
  type GetUserActionsData,
  type GetUserActionsError,
  type GetUserActionsResponse,
  type UploadKnowledgeFile1Data,
  type UploadKnowledgeFile1Error,
  type UploadKnowledgeFile1Response,
  type GetImageFileData,
  type GetImageFileError,
  type GetImageFileResponse,
  type GetFileContentData,
  type GetFileContentError,
  type GetFileContentResponse,
  type GetUserAgentsData,
  type GetUserAgentsError,
  type GetUserAgentsResponse,
  type GetTrendingAgentsData,
  type GetTrendingAgentsError,
  type GetTrendingAgentsResponse,
  type GetAgentStarUsersData,
  type GetAgentStarUsersError,
  type GetAgentStarUsersResponse,
  type SearchAgentByKeyWordData,
  type SearchAgentByKeyWordError,
  type SearchAgentByKeyWordResponse,
  type GetAgentReleaseHistoryData,
  type GetAgentReleaseHistoryError,
  type GetAgentReleaseHistoryResponse,
  type GetPublicAgentsData,
  type GetPublicAgentsError,
  type GetPublicAgentsResponse,
  type DownloadAgentMarkdownData,
  type DownloadAgentMarkdownError,
  type DownloadAgentMarkdownResponse,
  type GetAgentForkUsersData,
  type GetAgentForkUsersError,
  type GetAgentForkUsersResponse,
  type ListForkedAgentsData,
  type ListForkedAgentsError,
  type ListForkedAgentsResponse,
  type CountForksData,
  type CountForksError,
  type CountForksResponse,
  type ExportAgentData,
  type ExportAgentError,
  type ExportAgentResponse,
  type GetAgentByUserNameAndAgentNameData,
  type GetAgentByUserNameAndAgentNameError,
  type GetAgentByUserNameAndAgentNameResponse,
  type CleanCreationChatSessionError,
  type CleanCreationChatSessionResponse,
  type DeleteFileData,
  type DeleteFileError,
  type DeleteFileResponse,
  type DeleteFilesData,
  type DeleteFilesError,
  type DeleteFilesResponse,
  type DeleteAgentFileData,
  type DeleteAgentFileError,
  type DeleteAgentFileResponse,
  GetCurrentUserProfileResponseTransformer,
  GetAgentByIdResponseTransformer,
  CreateAgentResponseTransformer,
  ListStarredAgentsResponseTransformer,
  NavigationChatResponseTransformer,
  UploadToolFileResponseTransformer,
  GetFileInfosByIdsResponseTransformer,
  SignupResponseTransformer,
  ImportAgentResponseTransformer,
  ForkAgentResponseTransformer,
  ListUsersResponseTransformer,
  GetRecentUserActionsResponseTransformer,
  GetUserProfileByUsernameResponseTransformer,
  GetUserProfileResponseTransformer,
  GetUserFollowingResponseTransformer,
  GetUserFollowersResponseTransformer,
  GetUserActionsResponseTransformer,
  UploadKnowledgeFile1ResponseTransformer,
  GetUserAgentsResponseTransformer,
  GetTrendingAgentsResponseTransformer,
  GetAgentStarUsersResponseTransformer,
  SearchAgentByKeyWordResponseTransformer,
  GetAgentReleaseHistoryResponseTransformer,
  GetPublicAgentsResponseTransformer,
  GetAgentForkUsersResponseTransformer,
  ListForkedAgentsResponseTransformer,
  GetAgentByUserNameAndAgentNameResponseTransformer,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * 获取当前用户资料
 * 获取当前用户资料
 */
export const getCurrentUserProfile = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetCurrentUserProfileResponse,
    GetCurrentUserProfileError
  >({
    ...options,
    url: '/api/v1/users/profile',
    responseTransformer: GetCurrentUserProfileResponseTransformer,
  });
};

/**
 * 更新当前用户资料
 * 更新当前用户资料
 */
export const updateCurrentUserProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCurrentUserProfileData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    UpdateCurrentUserProfileResponse,
    UpdateCurrentUserProfileError
  >({
    ...options,
    url: '/api/v1/users/profile',
  });
};

/**
 * 修改文件内容
 * 根据文件ID修改文件内容
 */
export const updateFileContent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFileContentData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    UpdateFileContentResponse,
    UpdateFileContentError
  >({
    ...options,
    url: '/api/v1/file/content',
  });
};

/**
 * 获取Agent
 * 根据ID获取指定的Agent
 */
export const getAgentById = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetAgentByIdResponse,
    GetAgentByIdError
  >({
    ...options,
    url: '/api/v1/agents',
    responseTransformer: GetAgentByIdResponseTransformer,
  });
};

/**
 * 更新Agent信息
 */
export const updateAgent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    UpdateAgentResponse,
    UpdateAgentError
  >({
    ...options,
    url: '/api/v1/agents',
  });
};

/**
 * 创建Agent
 * 创建一个新的Agent
 */
export const createAgent = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    CreateAgentResponse,
    CreateAgentError
  >({
    ...options,
    url: '/api/v1/agents',
    responseTransformer: CreateAgentResponseTransformer,
  });
};

/**
 * 删除Agent信息
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteAgentResponse,
    DeleteAgentError
  >({
    ...options,
    url: '/api/v1/agents',
  });
};

/**
 * 获取用户收藏的Agent列表
 */
export const listStarredAgents = <ThrowOnError extends boolean = false>(
  options: Options<ListStarredAgentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    ListStarredAgentsResponse,
    ListStarredAgentsError
  >({
    ...options,
    url: '/api/v1/agents/star',
    responseTransformer: ListStarredAgentsResponseTransformer,
  });
};

/**
 * 收藏Agent
 */
export const starAgent = <ThrowOnError extends boolean = false>(
  options: Options<StarAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    StarAgentResponse,
    StarAgentError
  >({
    ...options,
    url: '/api/v1/agents/star',
  });
};

/**
 * 取消收藏Agent
 */
export const unStarAgent = <ThrowOnError extends boolean = false>(
  options: Options<UnStarAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    UnStarAgentResponse,
    UnStarAgentError
  >({
    ...options,
    url: '/api/v1/agents/star',
  });
};

/**
 * 发布Agent
 * 发布指定ID的Agent
 */
export const publishAgent = <ThrowOnError extends boolean = false>(
  options: Options<PublishAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PublishAgentResponse,
    PublishAgentError
  >({
    ...options,
    url: '/api/v1/agents/publish',
  });
};

/**
 * 关注用户
 * 关注指定用户
 */
export const followUser = <ThrowOnError extends boolean = false>(
  options: Options<FollowUserData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    FollowUserResponse,
    FollowUserError
  >({
    ...options,
    url: '/api/v1/users/follow',
  });
};

/**
 * 取消关注用户
 * 取消对指定用户的关注
 */
export const unfollowUser = <ThrowOnError extends boolean = false>(
  options: Options<UnfollowUserData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    UnfollowUserResponse,
    UnfollowUserError
  >({
    ...options,
    url: '/api/v1/users/follow',
  });
};

/**
 * 导航接口
 * 调用liteAgent 判断是否进入搜索页面还是创建页面
 */
export const navigationChat = <ThrowOnError extends boolean = false>(
  options: Options<NavigationChatData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    NavigationChatResponse,
    NavigationChatError
  >({
    ...options,
    url: '/api/v1/liteAgent/navigation',
    responseTransformer: NavigationChatResponseTransformer,
  });
};

/**
 * agent创作编辑接口
 * 调用liteAgent 生成ihub_agent.md
 */
export const creationChat = <ThrowOnError extends boolean = false>(
  options: Options<CreationChatData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    CreationChatResponse,
    CreationChatError
  >({
    ...options,
    url: '/api/v1/liteAgent/creation/chat',
  });
};

/**
 * 上传工具描述文件
 * 上传JSON或YML格式的工具描述文件
 */
export const uploadToolFile = <ThrowOnError extends boolean = false>(
  options?: Options<UploadToolFileData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    UploadToolFileResponse,
    UploadToolFileError
  >({
    ...options,
    url: '/api/v1/file/tool',
    responseTransformer: UploadToolFileResponseTransformer,
  });
};

/**
 * 根据ID列表获取文件信息
 * 根据ID列表获取文件信息
 */
export const getFileInfosByIds = <ThrowOnError extends boolean = false>(
  options: Options<GetFileInfosByIdsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    GetFileInfosByIdsResponse,
    GetFileInfosByIdsError
  >({
    ...options,
    url: '/api/v1/file/list',
    responseTransformer: GetFileInfosByIdsResponseTransformer,
  });
};

/**
 * 上传知识库文件
 * 上传doc,ppt,pdf,txt文件,返回文件id,可查询文件上传进度
 */
export const uploadKnowledgeFile = <ThrowOnError extends boolean = false>(
  options?: Options<UploadKnowledgeFileData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    UploadKnowledgeFileResponse,
    UploadKnowledgeFileError
  >({
    ...options,
    url: '/api/v1/file/knowledge',
  });
};

/**
 * 上传用户头像
 * 上传用户头像文件，支持png,jpeg,jpg,gif,bmp格式
 */
export const uploadAvatarFile = <ThrowOnError extends boolean = false>(
  options?: Options<UploadAvatarFileData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    UploadAvatarFileResponse,
    UploadAvatarFileError
  >({
    ...options,
    url: '/api/v1/file/avatar',
  });
};

/**
 * 用户注册
 * 新用户注册账户
 */
export const signup = <ThrowOnError extends boolean = false>(
  options: Options<SignupData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    SignupResponse,
    SignupError
  >({
    ...options,
    url: '/api/v1/auth/signup',
    responseTransformer: SignupResponseTransformer,
  });
};

/**
 * 刷新令牌
 * 使用刷新令牌获取新的访问令牌
 */
export const refreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    RefreshTokenResponse,
    RefreshTokenError
  >({
    ...options,
    url: '/api/v1/auth/refresh',
  });
};

/**
 * 用户登出
 * 用户登出系统
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    LogoutResponse,
    LogoutError
  >({
    ...options,
    url: '/api/v1/auth/logout',
  });
};

/**
 * 用户登录
 * 用户使用邮箱和密码进行登录
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    LoginResponse,
    LoginError
  >({
    ...options,
    url: '/api/v1/auth/login',
  });
};

/**
 * 导入Agent
 * 通过上传agent文件导入Agent配置
 */
export const importAgent = <ThrowOnError extends boolean = false>(
  options?: Options<ImportAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    ImportAgentResponse,
    ImportAgentError
  >({
    ...options,
    url: '/api/v1/agents/import',
    responseTransformer: ImportAgentResponseTransformer,
  });
};

/**
 * Fork Agent
 */
export const forkAgent = <ThrowOnError extends boolean = false>(
  options: Options<ForkAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    ForkAgentResponse,
    ForkAgentError
  >({
    ...options,
    url: '/api/v1/agents/fork',
    responseTransformer: ForkAgentResponseTransformer,
  });
};

/**
 * 验证验证码
 * 验证邮箱验证码是否正确
 */
export const verifyCode = <ThrowOnError extends boolean = false>(
  options: Options<VerifyCodeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    VerifyCodeResponse,
    VerifyCodeError
  >({
    ...options,
    url: '/api/v1/account/verify-code',
  });
};

/**
 * 验证图片验证码
 * 验证图片验证码是否正确
 */
export const verifyCaptcha = <ThrowOnError extends boolean = false>(
  options: Options<VerifyCaptchaData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    VerifyCaptchaResponse,
    VerifyCaptchaError
  >({
    ...options,
    url: '/api/v1/account/verify-captcha',
  });
};

/**
 * 发送注册验证码
 * 向指定邮箱发送注册验证码
 */
export const sendRegistrationCode = <ThrowOnError extends boolean = false>(
  options: Options<SendRegistrationCodeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    SendRegistrationCodeResponse,
    SendRegistrationCodeError
  >({
    ...options,
    url: '/api/v1/account/send-registration-code',
  });
};

/**
 * 发送手机验证码
 * 向指定手机发送注册验证码
 */
export const sendPhoneCode = <ThrowOnError extends boolean = false>(
  options: Options<SendPhoneCodeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    SendPhoneCodeResponse,
    SendPhoneCodeError
  >({
    ...options,
    url: '/api/v1/account/send-phone-code',
  });
};

/**
 * 发送忘记密码验证码
 * 向指定邮箱发送忘记密码验证码
 */
export const sendForgetPasswordCode = <ThrowOnError extends boolean = false>(
  options: Options<SendForgetPasswordCodeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    SendForgetPasswordCodeResponse,
    SendForgetPasswordCodeError
  >({
    ...options,
    url: '/api/v1/account/send-forget-password-code',
  });
};

/**
 * 重置密码
 * 重置密码
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    ResetPasswordResponse,
    ResetPasswordError
  >({
    ...options,
    url: '/api/v1/account/reset',
  });
};

/**
 * 修改当前用户密码
 * 修改当前用户密码
 */
export const changePassword = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    ChangePasswordResponse,
    ChangePasswordError
  >({
    ...options,
    url: '/api/v1/account/change-password',
  });
};

/**
 * 获取图片验证码
 * 生成并获取图片验证码
 */
export const getCaptcha = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    GetCaptchaResponse,
    GetCaptchaError
  >({
    ...options,
    url: '/api/v1/account/captcha',
  });
};

/**
 * 分页获取用户列表
 * 分页获取用户列表
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    ListUsersResponse,
    ListUsersError
  >({
    ...options,
    url: '/api/v1/users',
    responseTransformer: ListUsersResponseTransformer,
  });
};

/**
 * 获取用户统计信息
 * 根据用户ID获取指定用户的统计数据
 */
export const getUserStats = <ThrowOnError extends boolean = false>(
  options: Options<GetUserStatsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserStatsResponse,
    GetUserStatsError
  >({
    ...options,
    url: '/api/v1/users/stats',
  });
};

/**
 * 获取用户最近的操作日志
 * 获取指定用户的最近操作日志
 */
export const getRecentUserActions = <ThrowOnError extends boolean = false>(
  options: Options<GetRecentUserActionsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetRecentUserActionsResponse,
    GetRecentUserActionsError
  >({
    ...options,
    url: '/api/v1/users/recent-actions',
    responseTransformer: GetRecentUserActionsResponseTransformer,
  });
};

/**
 * 获取用户资料
 * 根据用户名获取指定用户的资料信息
 */
export const getUserProfileByUsername = <ThrowOnError extends boolean = false>(
  options: Options<GetUserProfileByUsernameData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserProfileByUsernameResponse,
    GetUserProfileByUsernameError
  >({
    ...options,
    url: '/api/v1/users/profile-by-username',
    responseTransformer: GetUserProfileByUsernameResponseTransformer,
  });
};

/**
 * 获取用户资料
 * 根据用户ID获取指定用户的资料信息
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(
  options: Options<GetUserProfileData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserProfileResponse,
    GetUserProfileError
  >({
    ...options,
    url: '/api/v1/users/profile-by-id',
    responseTransformer: GetUserProfileResponseTransformer,
  });
};

/**
 * 获取用户关注列表
 * 获取指定用户关注的人列表
 */
export const getUserFollowing = <ThrowOnError extends boolean = false>(
  options: Options<GetUserFollowingData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserFollowingResponse,
    GetUserFollowingError
  >({
    ...options,
    url: '/api/v1/users/following',
    responseTransformer: GetUserFollowingResponseTransformer,
  });
};

/**
 * 获取用户关注者列表
 * 获取指定用户的关注者列表
 */
export const getUserFollowers = <ThrowOnError extends boolean = false>(
  options: Options<GetUserFollowersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserFollowersResponse,
    GetUserFollowersError
  >({
    ...options,
    url: '/api/v1/users/followers',
    responseTransformer: GetUserFollowersResponseTransformer,
  });
};

/**
 * 分页获取用户操作日志
 * 分页获取指定用户操作日志
 */
export const getUserActions = <ThrowOnError extends boolean = false>(
  options: Options<GetUserActionsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserActionsResponse,
    GetUserActionsError
  >({
    ...options,
    url: '/api/v1/users/actions',
    responseTransformer: GetUserActionsResponseTransformer,
  });
};

/**
 * 获取知识库上传进度
 * 获取知识库上传进度
 */
export const uploadKnowledgeFile1 = <ThrowOnError extends boolean = false>(
  options: Options<UploadKnowledgeFile1Data, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    UploadKnowledgeFile1Response,
    UploadKnowledgeFile1Error
  >({
    ...options,
    url: '/api/v1/file/knowledge/progress',
    responseTransformer: UploadKnowledgeFile1ResponseTransformer,
  });
};

/**
 * 获取图片文件
 * 获取图片文件
 */
export const getImageFile = <ThrowOnError extends boolean = false>(
  options: Options<GetImageFileData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetImageFileResponse,
    GetImageFileError
  >({
    ...options,
    url: '/api/v1/file/images/{imagesFileName}',
  });
};

/**
 * 获取文件内容
 * 根据文件ID获取文件内容，支持文本和图片
 */
export const getFileContent = <ThrowOnError extends boolean = false>(
  options: Options<GetFileContentData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetFileContentResponse,
    GetFileContentError
  >({
    ...options,
    url: '/api/v1/file/content/{id}',
  });
};

/**
 * 获取用户Agent列表
 */
export const getUserAgents = <ThrowOnError extends boolean = false>(
  options: Options<GetUserAgentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetUserAgentsResponse,
    GetUserAgentsError
  >({
    ...options,
    url: '/api/v1/agents/user',
    responseTransformer: GetUserAgentsResponseTransformer,
  });
};

/**
 * 获取热门Agent列表
 * 分页获取热门Agent列表
 */
export const getTrendingAgents = <ThrowOnError extends boolean = false>(
  options: Options<GetTrendingAgentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetTrendingAgentsResponse,
    GetTrendingAgentsError
  >({
    ...options,
    url: '/api/v1/agents/trending',
    responseTransformer: GetTrendingAgentsResponseTransformer,
  });
};

/**
 * 获取收藏了指定Agent的用户列表
 * 分页获取收藏了指定Agent的用户列表
 */
export const getAgentStarUsers = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentStarUsersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetAgentStarUsersResponse,
    GetAgentStarUsersError
  >({
    ...options,
    url: '/api/v1/agents/star/users',
    responseTransformer: GetAgentStarUsersResponseTransformer,
  });
};

/**
 * 根据关键字搜索 agent
 * 根据关键字搜索 agent
 */
export const searchAgentByKeyWord = <ThrowOnError extends boolean = false>(
  options: Options<SearchAgentByKeyWordData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    SearchAgentByKeyWordResponse,
    SearchAgentByKeyWordError
  >({
    ...options,
    url: '/api/v1/agents/search-agent',
    responseTransformer: SearchAgentByKeyWordResponseTransformer,
  });
};

/**
 * 分页查询Agent发布历史
 * 分页查询Agent发布历史
 */
export const getAgentReleaseHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentReleaseHistoryData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetAgentReleaseHistoryResponse,
    GetAgentReleaseHistoryError
  >({
    ...options,
    url: '/api/v1/agents/release/history',
    responseTransformer: GetAgentReleaseHistoryResponseTransformer,
  });
};

/**
 * 获取公共Agent列表
 * 分页获取公共Agent列表
 */
export const getPublicAgents = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicAgentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetPublicAgentsResponse,
    GetPublicAgentsError
  >({
    ...options,
    url: '/api/v1/agents/public',
    responseTransformer: GetPublicAgentsResponseTransformer,
  });
};

/**
 * 下载agent的md内容
 * 下载指定ID的agent的Markdown内容，文件名称为agent的名称.md
 */
export const downloadAgentMarkdown = <ThrowOnError extends boolean = false>(
  options: Options<DownloadAgentMarkdownData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    DownloadAgentMarkdownResponse,
    DownloadAgentMarkdownError
  >({
    ...options,
    url: '/api/v1/agents/md/{id}',
  });
};

/**
 * 获取fork了指定Agent的用户列表
 * 分页获取fork了指定Agent的用户列表
 */
export const getAgentForkUsers = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentForkUsersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetAgentForkUsersResponse,
    GetAgentForkUsersError
  >({
    ...options,
    url: '/api/v1/agents/fork/users',
    responseTransformer: GetAgentForkUsersResponseTransformer,
  });
};

/**
 * 分页获取fork了某个agent的agent列表
 * 分页获取fork了某个agent的agent列表
 */
export const listForkedAgents = <ThrowOnError extends boolean = false>(
  options: Options<ListForkedAgentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    ListForkedAgentsResponse,
    ListForkedAgentsError
  >({
    ...options,
    url: '/api/v1/agents/fork/list',
    responseTransformer: ListForkedAgentsResponseTransformer,
  });
};

/**
 * 获取Agent的Fork数量
 */
export const countForks = <ThrowOnError extends boolean = false>(
  options: Options<CountForksData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    CountForksResponse,
    CountForksError
  >({
    ...options,
    url: '/api/v1/agents/fork/count',
  });
};

/**
 * 导出Agent
 * 导出指定ID的Agent为agent文件
 */
export const exportAgent = <ThrowOnError extends boolean = false>(
  options: Options<ExportAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    ExportAgentResponse,
    ExportAgentError
  >({
    ...options,
    url: '/api/v1/agents/export',
  });
};

/**
 * 根据用户名和agent名称获取指定的Agent
 * 根据用户名和agent名称获取指定的Agent
 */
export const getAgentByUserNameAndAgentName = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAgentByUserNameAndAgentNameData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetAgentByUserNameAndAgentNameResponse,
    GetAgentByUserNameAndAgentNameError
  >({
    ...options,
    url: '/api/v1/agents/by-name',
    responseTransformer: GetAgentByUserNameAndAgentNameResponseTransformer,
  });
};

/**
 * 清空agent创作编辑会话
 * 清空agent创作编辑会话
 */
export const cleanCreationChatSession = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    CleanCreationChatSessionResponse,
    CleanCreationChatSessionError
  >({
    ...options,
    url: '/api/v1/liteAgent/creation/clean-session',
  });
};

/**
 * 删除文件信息
 * 根据ID删除指定的文件信息
 */
export const deleteFile = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFileData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteFileResponse,
    DeleteFileError
  >({
    ...options,
    url: '/api/v1/file/{id}',
  });
};

/**
 * 批量删除文件信息
 * 根据ID列表批量删除文件信息
 */
export const deleteFiles = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFilesData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteFilesResponse,
    DeleteFilesError
  >({
    ...options,
    url: '/api/v1/file/batch',
  });
};

/**
 * 删除Agent知识库、工具文件
 */
export const deleteAgentFile = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentFileData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteAgentFileResponse,
    DeleteAgentFileError
  >({
    ...options,
    url: '/api/v1/agents/files',
  });
};
