// This file is auto-generated by @hey-api/openapi-ts

export type RVoid = {
  code?: number;
  msg?: string;
  data?: unknown;
};

/**
 * 更新用户信息DTO
 */
export type UpdateUserDTO = {
  /**
   * 用户唯一标识
   */
  id: string;
  /**
   * 用户邮箱
   */
  email?: string;
  /**
   * 昵称
   */
  nickName?: string;
  /**
   * 用户头像URL
   */
  avatar?: string;
  /**
   * 用户简介
   */
  bio?: string;
  /**
   * 用户位置
   */
  location?: string;
  /**
   * 用户网站
   */
  website?: string;
};

export type RBoolean = {
  code?: number;
  msg?: string;
  data?: boolean;
};

/**
 * 更新文件内容
 */
export type UpdateFileContentDTO = {
  /**
   * 文件ID
   */
  id: string;
  /**
   * 文件内容
   */
  content: string;
};

/**
 * AgentLicense信息DTO
 */
export type AgentLicenseDTO = {
  /**
   * License唯一标识,创建时不需要传，修改时必传
   */
  id?: string;
  /**
   * Agent唯一标识
   */
  agentId?: string;
  /**
   * 协议类型
   */
  type?:
    | 'MIT'
    | 'APACHE_2_0'
    | 'GPL_3_0'
    | 'BSD_3_CLAUSE'
    | 'AGPL_3_0'
    | 'PROPRIETARY'
    | 'CUSTOM';
  /**
   * 官方协议或自定义协议链接
   */
  url?: string;
  /**
   * 若为自定义协议，可直接存放文本
   */
  text?: string;
  /**
   * 是否允许 Fork，前端显示或限制逻辑可用
   */
  allowFork?: boolean;
  /**
   * 创建时间
   */
  createTime?: Date;
  /**
   * 更新时间
   */
  updateTime?: Date;
};

/**
 * 协议类型
 */
export enum type {
  MIT = 'MIT',
  APACHE_2_0 = 'APACHE_2_0',
  GPL_3_0 = 'GPL_3_0',
  BSD_3_CLAUSE = 'BSD_3_CLAUSE',
  AGPL_3_0 = 'AGPL_3_0',
  PROPRIETARY = 'PROPRIETARY',
  CUSTOM = 'CUSTOM',
}

/**
 * Agent更新信息DTO
 */
export type UpdateAgentDTO = {
  /**
   * Agent唯一标识
   */
  id?: string;
  /**
   * Agent名称
   */
  name: string;
  /**
   * Agent描述
   */
  description?: string;
  /**
   * 平台类型 (LiteAgent、Dify、Coze等)
   */
  platform: 'LiteAgent' | 'Dify' | 'Coze';
  /**
   * md内容
   */
  mdContent: string;
  /**
   * 工具文件id列表
   */
  toolFileIdList?: Array<string>;
  /**
   * 知识库md文档id列表
   */
  docsFileIdList?: Array<string>;
  /**
   * 分类
   */
  category?: string;
  /**
   * 是否公开
   */
  isPublic?: boolean;
  /**
   * 标签列表
   */
  tags?: Array<string>;
  /**
   * license信息
   */
  license?: AgentLicenseDTO;
};

/**
 * 平台类型 (LiteAgent、Dify、Coze等)
 */
export enum platform {
  LITE_AGENT = 'LiteAgent',
  DIFY = 'Dify',
  COZE = 'Coze',
}

export type RObject = {
  code?: number;
  msg?: string;
  data?: unknown;
};

/**
 * 发布Agent信息DTO
 */
export type PublishAgentDTO = {
  /**
   * Agent ID
   */
  id: string;
  /**
   * 版本号
   */
  version: string;
  /**
   * 发布说明
   */
  releaseNotes?: string;
};

/**
 * agent 聊天DTO
 */
export type AgentChatDTO = {
  /**
   * 聊天内容
   */
  content?: string;
};

/**
 * Agent信息DTO
 */
export type AgentDTO = {
  /**
   * Agent唯一标识
   */
  id?: string;
  /**
   * Agent名称
   */
  name: string;
  /**
   * Agent描述
   */
  description?: string;
  /**
   * 平台类型 (LiteAgent、Dify、Coze等)
   */
  platform: 'LiteAgent' | 'Dify' | 'Coze';
  /**
   * md内容
   */
  mdContent: string;
  /**
   * 工具文件id列表
   */
  toolFileIdList?: Array<string>;
  /**
   * 知识库md文档id列表
   */
  docsFileIdList?: Array<string>;
  /**
   * 摘要文档id
   */
  documentId?: string;
  /**
   * 作者用户ID
   */
  authorId?: string;
  /**
   * 作者用户名
   */
  authorName?: string;
  /**
   * 作者昵称
   */
  authorNickName?: string;
  /**
   * 分类
   */
  category?: string;
  /**
   * 是否公开
   */
  isPublic?: boolean;
  /**
   * 标签列表
   */
  tags?: Array<string>;
  /**
   * 版本号
   */
  version?: string;
  /**
   * 收藏数
   */
  stars?: number;
  /**
   * 分叉数
   */
  forks?: number;
  /**
   * 浏览数
   */
  views?: number;
  /**
   * 是否发布
   */
  isPublished?: boolean;
  /**
   * 创建时间
   */
  createTime?: Date;
  /**
   * 更新时间
   */
  updateTime?: Date;
  /**
   * 是否已star
   */
  isStarred?: boolean;
  /**
   * fork 信息
   */
  forkInfo?: ForkDTO;
  /**
   * license信息
   */
  license?: AgentLicenseDTO;
};

/**
 * Fork信息DTO
 */
export type ForkDTO = {
  /**
   * Fork记录唯一标识
   */
  id?: string;
  /**
   * Fork用户ID
   */
  userId?: string;
  /**
   * 原始Agent ID
   */
  originalAgentId?: string;
  /**
   * Fork后的新Agent ID
   */
  forkedAgentId?: string;
  /**
   * 原始Agent名称
   */
  originalAgentName?: string;
  /**
   * 原始Agent 作者id
   */
  originalAgentAuthorId?: string;
  /**
   * 原始Agent 作者名称
   */
  originalAgentAuthorName?: string;
  /**
   * 原始Agent 作者昵称
   */
  originalAgentAuthorNickName?: string;
  /**
   * 创建时间
   */
  createTime?: Date;
};

/**
 * 导航结果DTO
 */
export type NavigationResultDTO = {
  /**
   * 导航结果
   */
  text?: string;
  /**
   * 导航结果类型
   */
  type?: string;
  /**
   * 搜索结果
   */
  agentDTOS?: Array<AgentDTO>;
};

export type RNavigationResultDTO = {
  code?: number;
  msg?: string;
  data?: NavigationResultDTO;
};

/**
 * agent创作编辑接口DTO
 */
export type CreationChatDTO = {
  /**
   * 用户指令
   */
  cmd: string;
  /**
   * 工具文件id列表
   */
  toolFileIdList?: Array<string>;
  /**
   * 知识库md文档id列表
   */
  docsFileIdList?: Array<string>;
};

export type ServerSentEventAgentMessage = unknown;

export type FileDocMetadataDTO = {
  name?: string;
  separator?: string;
};

/**
 * 文件信息DTO
 */
export type FileInfoDTO = {
  /**
   * 文件ID
   */
  id?: string;
  /**
   * 完整文件名
   */
  fileName?: string;
  /**
   * 文件大小 (字节)
   */
  fileSize?: number;
  /**
   * 文件类型
   */
  fileType?: string;
  /**
   * 上传类型
   */
  type?: 'TOOLS' | 'AVATARS' | 'KNOWLEDGE';
  /**
   * md5
   */
  md5?: string;
  /**
   * 文档文件的元数据 从liteagent导入的需保留原数据，否则导出时生成
   */
  metadata?: FileDocMetadataDTO;
  /**
   * 关联图片文件ID
   */
  imagesFileIds?: Array<string>;
  /**
   * 上传用户ID
   */
  userId?: string;
  /**
   * 上传时间
   */
  uploadTime?: Date;
};

/**
 * 上传类型
 */
export enum type2 {
  TOOLS = 'TOOLS',
  AVATARS = 'AVATARS',
  KNOWLEDGE = 'KNOWLEDGE',
}

export type RFileInfoDTO = {
  code?: number;
  msg?: string;
  data?: FileInfoDTO;
};

export type RListFileInfoDTO = {
  code?: number;
  msg?: string;
  data?: Array<FileInfoDTO>;
};

export type RString = {
  code?: number;
  msg?: string;
  data?: string;
};

/**
 * 注册请求DTO
 */
export type SignupRequestDTO = {
  /**
   * 用户名
   */
  userName?: string;
  /**
   * 邮箱地址
   */
  email: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 头像地址
   */
  avatar?: string;
  /**
   * 密码
   */
  password?: string;
};

export type RUserDTO = {
  code?: number;
  msg?: string;
  data?: UserDTO;
};

/**
 * 用户信息DTO
 */
export type UserDTO = {
  /**
   * 用户唯一标识
   */
  id: string;
  /**
   * 用户邮箱
   */
  email?: string;
  /**
   * 用户名
   */
  userName?: string;
  /**
   * 昵称
   */
  nickName?: string;
  /**
   * 用户头像URL
   */
  avatar?: string;
  /**
   * 用户简介
   */
  bio?: string;
  /**
   * 用户位置
   */
  location?: string;
  /**
   * 用户网站
   */
  website?: string;
  /**
   * 用户角色
   */
  role?: 'ROLE_USER' | 'ROLE_ADMIN';
  /**
   * 用户状态
   */
  status?: 'NORMAL' | 'LOCKED' | 'DELETED';
  /**
   * 是否被当前用户关注
   */
  following?: boolean;
  /**
   * 创建时间
   */
  createTime?: Date;
  /**
   * 更新时间
   */
  updateTime?: Date;
  /**
   * 最后登录时间
   */
  lastLoginTime?: Date;
};

/**
 * 用户角色
 */
export enum role {
  ROLE_USER = 'ROLE_USER',
  ROLE_ADMIN = 'ROLE_ADMIN',
}

/**
 * 用户状态
 */
export enum status {
  NORMAL = 'NORMAL',
  LOCKED = 'LOCKED',
  DELETED = 'DELETED',
}

/**
 * 登录请求DTO
 */
export type LoginRequestDTO = {
  /**
   * 邮箱地址
   */
  email?: string;
  /**
   * 密码
   */
  password: string;
};

export type RSaTokenInfo = {
  code?: number;
  msg?: string;
  data?: SaTokenInfo;
};

export type SaTokenInfo = {
  tokenName?: string;
  tokenValue?: string;
  isLogin?: boolean;
  loginId?: unknown;
  loginType?: string;
  tokenTimeout?: number;
  sessionTimeout?: number;
  tokenSessionTimeout?: number;
  tokenActiveTimeout?: number;
  loginDeviceType?: string;
  tag?: string;
};

/**
 * 创建Agent信息DTO
 */
export type CreateAgentDTO = {
  /**
   * AgentId
   */
  id?: string;
  /**
   * Agent名称
   */
  name: string;
  /**
   * Agent描述
   */
  description?: string;
  /**
   * 平台类型 (LiteAgent、Dify、Coze等)
   */
  platform: 'LiteAgent' | 'Dify' | 'Coze';
  /**
   * md内容
   */
  mdContent: string;
  /**
   * 工具文件id列表
   */
  toolFileIdList?: Array<string>;
  /**
   * 知识库md文档id列表
   */
  docsFileIdList?: Array<string>;
  /**
   * license信息
   */
  license?: AgentLicenseDTO;
  /**
   * 是否公开
   */
  isPublic?: boolean;
};

export type RAgentDTO = {
  code?: number;
  msg?: string;
  data?: AgentDTO;
};

/**
 * Agent Fork请求DTO
 */
export type ForkRequestDTO = {
  /**
   * Fork后的Agent名称（可选，如果不提供则使用原名称 + " (Fork)"）
   */
  name?: string;
  /**
   * Fork后的Agent描述（可选，如果不提供则使用原描述）
   */
  description?: string;
};

/**
 * 验证码验证请求DTO
 */
export type VerifyCodeDTO = {
  /**
   * 邮箱地址
   */
  email?: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 验证码
   */
  code: string;
};

/**
 * 图片验证码DTO
 */
export type CaptchaDTO = {
  /**
   * 验证码key
   */
  captchaKey: string;
  /**
   * 用户输入的验证码
   */
  captchaCode: string;
};

/**
 * 发送验证码DTO
 */
export type SendVerifyCodeDTO = {
  /**
   * 邮箱地址
   */
  email?: string;
  /**
   * 手机号
   */
  phone?: string;
};

/**
 * 重置密码请求DTO
 */
export type ResetPasswordDTO = {
  /**
   * 邮箱地址
   */
  email: string;
  /**
   * 新密码
   */
  newPassword: string;
};

/**
 * 修改密码请求DTO
 */
export type ChangePasswordDTO = {
  /**
   * 当前密码
   */
  currentPassword: string;
  /**
   * 新密码
   */
  newPassword?: string;
};

export type PageResultUserDTO = {
  pageNum?: number;
  pageSize?: number;
  totalSize?: number;
  totalPages?: number;
  contentData?: Array<UserDTO>;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
  firstPage?: boolean;
  lastPage?: boolean;
};

export type RPageResultUserDTO = {
  code?: number;
  msg?: string;
  data?: PageResultUserDTO;
};

export type RUserStatsDTO = {
  code?: number;
  msg?: string;
  data?: UserStatsDTO;
};

/**
 * 用户统计数据DTO
 */
export type UserStatsDTO = {
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 关注数
   */
  followingCount?: number;
  /**
   * 粉丝数
   */
  followerCount?: number;
  /**
   * 收藏数
   */
  starCount?: number;
  /**
   * 分叉数
   */
  forkCount?: number;
  /**
   * 创建的Agent数
   */
  agentCount?: number;
  /**
   * 总浏览数
   */
  totalViews?: number;
};

export type RListUserActionLogDTO = {
  code?: number;
  msg?: string;
  data?: Array<UserActionLogDTO>;
};

/**
 * 操作日志DTO
 */
export type UserActionLogDTO = {
  /**
   * 日志唯一标识
   */
  id?: string;
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 用户名称
   */
  userName?: string;
  /**
   * 用户昵称
   */
  nickName?: string;
  /**
   * 操作类型
   */
  actionType?:
    | 'STAR_AGENT'
    | 'UNSTAR_AGENT'
    | 'FOLLOW_USER'
    | 'UNFOLLOW_USER'
    | 'EDIT_AGENT'
    | 'FORK_AGENT'
    | 'CREATE_AGENT'
    | 'DELETE_AGENT'
    | 'PUBLISH_AGENT';
  /**
   * 操作目标 agent ID
   */
  targetAgentId?: string;
  /**
   * 操作目标 agent 名称
   */
  targetAgentName?: string;
  /**
   * 操作目标 用户 ID
   */
  targetUserId?: string;
  /**
   * 操作目标 用户名称
   */
  targetUserName?: string;
  /**
   * 操作目标 用户昵称
   */
  targetUserNickName?: string;
  /**
   * 操作描述
   */
  description?: string;
  /**
   * 操作时间
   */
  actionTime?: Date;
};

/**
 * 操作类型
 */
export enum actionType {
  STAR_AGENT = 'STAR_AGENT',
  UNSTAR_AGENT = 'UNSTAR_AGENT',
  FOLLOW_USER = 'FOLLOW_USER',
  UNFOLLOW_USER = 'UNFOLLOW_USER',
  EDIT_AGENT = 'EDIT_AGENT',
  FORK_AGENT = 'FORK_AGENT',
  CREATE_AGENT = 'CREATE_AGENT',
  DELETE_AGENT = 'DELETE_AGENT',
  PUBLISH_AGENT = 'PUBLISH_AGENT',
}

export type PageResultUserActionLogDTO = {
  pageNum?: number;
  pageSize?: number;
  totalSize?: number;
  totalPages?: number;
  contentData?: Array<UserActionLogDTO>;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
  firstPage?: boolean;
  lastPage?: boolean;
};

export type RPageResultUserActionLogDTO = {
  code?: number;
  msg?: string;
  data?: PageResultUserActionLogDTO;
};

export type ConversionProgressDTO = {
  /**
   * 进度
   */
  progress?: number;
  /**
   * 状态
   */
  stage?: string;
  /**
   * 详情
   */
  detail?: string;
  /**
   * 文件信息,完成时返回
   */
  fileInfoDTO?: FileInfoDTO;
};

export type RConversionProgressDTO = {
  code?: number;
  msg?: string;
  data?: ConversionProgressDTO;
};

export type PageResultAgentDTO = {
  pageNum?: number;
  pageSize?: number;
  totalSize?: number;
  totalPages?: number;
  contentData?: Array<AgentDTO>;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
  firstPage?: boolean;
  lastPage?: boolean;
};

export type RPageResultAgentDTO = {
  code?: number;
  msg?: string;
  data?: PageResultAgentDTO;
};

export type RListAgentDTO = {
  code?: number;
  msg?: string;
  data?: Array<AgentDTO>;
};

/**
 * Agent发布历史记录DTO
 */
export type AgentReleaseDTO = {
  /**
   * 发布信息唯一标识
   */
  id?: string;
  /**
   * Agent ID
   */
  agentId?: string;
  /**
   * 版本号
   */
  version?: string;
  /**
   * 发布说明
   */
  releaseNotes?: string;
  /**
   * 创建时间
   */
  createTime?: Date;
};

export type PageResultAgentReleaseDTO = {
  pageNum?: number;
  pageSize?: number;
  totalSize?: number;
  totalPages?: number;
  contentData?: Array<AgentReleaseDTO>;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
  firstPage?: boolean;
  lastPage?: boolean;
};

export type RPageResultAgentReleaseDTO = {
  code?: number;
  msg?: string;
  data?: PageResultAgentReleaseDTO;
};

export type RInteger = {
  code?: number;
  msg?: string;
  data?: number;
};

export type GetCurrentUserProfileResponse = RUserDTO;

export type GetCurrentUserProfileError = RVoid;

export type UpdateCurrentUserProfileData = {
  body: UpdateUserDTO;
};

export type UpdateCurrentUserProfileResponse = RBoolean;

export type UpdateCurrentUserProfileError = RVoid;

export type UpdateFileContentData = {
  body: UpdateFileContentDTO;
};

export type UpdateFileContentResponse = RBoolean;

export type UpdateFileContentError = RVoid;

export type GetAgentByIdData = {
  query: {
    /**
     * Agent ID
     */
    id: string;
  };
};

export type GetAgentByIdResponse = RAgentDTO;

export type GetAgentByIdError = RVoid;

export type UpdateAgentData = {
  body: UpdateAgentDTO;
};

export type UpdateAgentResponse = RObject;

export type UpdateAgentError = RVoid;

export type CreateAgentData = {
  body: CreateAgentDTO;
};

export type CreateAgentResponse = RAgentDTO;

export type CreateAgentError = RVoid;

export type DeleteAgentData = {
  query: {
    id: string;
  };
};

export type DeleteAgentResponse = RObject;

export type DeleteAgentError = RVoid;

export type ListStarredAgentsData = {
  query: {
    /**
     * 分类
     */
    category?: string;
    /**
     * 当前页
     */
    pageNum: number;
    /**
     * 每页数量，最大100
     */
    pageSize: number;
    /**
     * 平台
     */
    platform?: string;
    /**
     * 查找内容
     */
    search?: string;
    /**
     * 排序
     */
    sort?: string;
    userId: string;
  };
};

export type ListStarredAgentsResponse = RPageResultAgentDTO;

export type ListStarredAgentsError = RVoid;

export type StarAgentData = {
  query: {
    agentId: string;
  };
};

export type StarAgentResponse = RBoolean;

export type StarAgentError = RVoid;

export type UnStarAgentData = {
  query: {
    agentId: string;
  };
};

export type UnStarAgentResponse = RBoolean;

export type UnStarAgentError = RVoid;

export type PublishAgentData = {
  body: PublishAgentDTO;
};

export type PublishAgentResponse = RBoolean;

export type PublishAgentError = RVoid;

export type FollowUserData = {
  query: {
    /**
     * 要关注的用户ID
     */
    userId: string;
  };
};

export type FollowUserResponse = RObject;

export type FollowUserError = RVoid;

export type UnfollowUserData = {
  query: {
    /**
     * 要取消关注的用户ID
     */
    userId: string;
  };
};

export type UnfollowUserResponse = RObject;

export type UnfollowUserError = RVoid;

export type NavigationChatData = {
  body: AgentChatDTO;
};

export type NavigationChatResponse = RNavigationResultDTO;

export type NavigationChatError = RVoid;

export type CreationChatData = {
  body: CreationChatDTO;
};

export type CreationChatResponse = Array<ServerSentEventAgentMessage>;

export type CreationChatError = RVoid;

export type UploadToolFileData = {
  body?: {
    file: Blob | File;
  };
};

export type UploadToolFileResponse = RFileInfoDTO;

export type UploadToolFileError = RVoid;

export type GetFileInfosByIdsData = {
  body: Array<string>;
};

export type GetFileInfosByIdsResponse = RListFileInfoDTO;

export type GetFileInfosByIdsError = RVoid;

export type UploadKnowledgeFileData = {
  body?: {
    file: Blob | File;
  };
};

export type UploadKnowledgeFileResponse = RString;

export type UploadKnowledgeFileError = RVoid;

export type UploadAvatarFileData = {
  body?: {
    file: Blob | File;
  };
};

export type UploadAvatarFileResponse = RString;

export type UploadAvatarFileError = RVoid;

export type SignupData = {
  body: SignupRequestDTO;
};

export type SignupResponse = RUserDTO;

export type SignupError = RVoid;

export type RefreshTokenResponse = RObject;

export type RefreshTokenError = RVoid;

export type LogoutResponse = RObject;

export type LogoutError = RVoid;

export type LoginData = {
  body: LoginRequestDTO;
};

export type LoginResponse = RSaTokenInfo;

export type LoginError = RVoid;

export type ImportAgentData = {
  body?: {
    file: Blob | File;
  };
};

export type ImportAgentResponse = RAgentDTO;

export type ImportAgentError = RVoid;

export type ForkAgentData = {
  body: ForkRequestDTO;
  query: {
    agentId: string;
  };
};

export type ForkAgentResponse = RAgentDTO;

export type ForkAgentError = RVoid;

export type VerifyCodeData = {
  body: VerifyCodeDTO;
};

export type VerifyCodeResponse = RBoolean;

export type VerifyCodeError = RVoid;

export type VerifyCaptchaData = {
  body: CaptchaDTO;
};

export type VerifyCaptchaResponse = RBoolean;

export type VerifyCaptchaError = RVoid;

export type SendRegistrationCodeData = {
  body: SendVerifyCodeDTO;
};

export type SendRegistrationCodeResponse = RVoid;

export type SendRegistrationCodeError = RVoid;

export type SendPhoneCodeData = {
  body: SendVerifyCodeDTO;
};

export type SendPhoneCodeResponse = RVoid;

export type SendPhoneCodeError = RVoid;

export type SendForgetPasswordCodeData = {
  body: SendVerifyCodeDTO;
};

export type SendForgetPasswordCodeResponse = RVoid;

export type SendForgetPasswordCodeError = RVoid;

export type ResetPasswordData = {
  body: ResetPasswordDTO;
};

export type ResetPasswordResponse = RVoid;

export type ResetPasswordError = RVoid;

export type ChangePasswordData = {
  body: ChangePasswordDTO;
};

export type ChangePasswordResponse = RBoolean;

export type ChangePasswordError = RVoid;

export type GetCaptchaResponse = unknown;

export type GetCaptchaError = RVoid;

export type ListUsersData = {
  query?: {
    /**
     * 搜索内容
     */
    content?: string;
    /**
     * 页码
     */
    pageNum?: number;
    /**
     * 每页数量
     */
    pageSize?: number;
    /**
     * 用户角色
     */
    userRole?: 'ROLE_USER' | 'ROLE_ADMIN';
  };
};

export type ListUsersResponse = RPageResultUserDTO;

export type ListUsersError = RVoid;

export type GetUserStatsData = {
  query: {
    /**
     * 是否统计所有agent，false时只统计公开的agent
     */
    allAgent: boolean;
    /**
     * 用户ID
     */
    userId: string;
  };
};

export type GetUserStatsResponse = RUserStatsDTO;

export type GetUserStatsError = RVoid;

export type GetRecentUserActionsData = {
  query: {
    /**
     * 返回日志条数限制，默认为10
     */
    limit?: number;
    /**
     * 用户ID
     */
    userId: string;
  };
};

export type GetRecentUserActionsResponse = RListUserActionLogDTO;

export type GetRecentUserActionsError = RVoid;

export type GetUserProfileByUsernameData = {
  query: {
    /**
     * 用户名
     */
    userName: string;
  };
};

export type GetUserProfileByUsernameResponse = RUserDTO;

export type GetUserProfileByUsernameError = RVoid;

export type GetUserProfileData = {
  query: {
    /**
     * 用户ID
     */
    userId: string;
  };
};

export type GetUserProfileResponse = RUserDTO;

export type GetUserProfileError = RVoid;

export type GetUserFollowingData = {
  query: {
    /**
     * 当前页
     */
    pageNum: number;
    /**
     * 每页数量，最大100
     */
    pageSize: number;
    /**
     * 用户ID
     */
    userId: string;
  };
};

export type GetUserFollowingResponse = RPageResultUserDTO;

export type GetUserFollowingError = RVoid;

export type GetUserFollowersData = {
  query: {
    /**
     * 当前页
     */
    pageNum: number;
    /**
     * 每页数量，最大100
     */
    pageSize: number;
    /**
     * 用户ID
     */
    userId: string;
  };
};

export type GetUserFollowersResponse = RPageResultUserDTO;

export type GetUserFollowersError = RVoid;

export type GetUserActionsData = {
  query: {
    /**
     * 当前页
     */
    pageNum?: number;
    /**
     * 每页数量，最大100
     */
    pageSize?: number;
    /**
     * 用户ID
     */
    userId: string;
  };
};

export type GetUserActionsResponse = RPageResultUserActionLogDTO;

export type GetUserActionsError = RVoid;

export type UploadKnowledgeFile1Data = {
  query: {
    fileId: string;
  };
};

export type UploadKnowledgeFile1Response = RConversionProgressDTO;

export type UploadKnowledgeFile1Error = RVoid;

export type GetImageFileData = {
  path: {
    /**
     * 图片文件名称
     */
    imagesFileName: string;
  };
};

export type GetImageFileResponse = Blob | File;

export type GetImageFileError = RVoid;

export type GetFileContentData = {
  path: {
    id: string;
  };
};

export type GetFileContentResponse = Blob | File;

export type GetFileContentError = RVoid;

export type GetUserAgentsData = {
  query: {
    pageNum: number;
    pageSize: number;
    search?: string;
    sort?: string;
    userId?: string;
    userName?: string;
  };
};

export type GetUserAgentsResponse = RPageResultAgentDTO;

export type GetUserAgentsError = RVoid;

export type GetTrendingAgentsData = {
  query: {
    /**
     * 页码
     */
    pageNum: number;
    /**
     * 每页数量
     */
    pageSize: number;
    /**
     * 平台
     */
    platform: string;
  };
};

export type GetTrendingAgentsResponse = RPageResultAgentDTO;

export type GetTrendingAgentsError = RVoid;

export type GetAgentStarUsersData = {
  query: {
    agentId: string;
    pageNum: number;
    pageSize: number;
  };
};

export type GetAgentStarUsersResponse = RPageResultUserDTO;

export type GetAgentStarUsersError = RVoid;

export type SearchAgentByKeyWordData = {
  query: {
    /**
     * keyWord
     */
    keyWord: string;
  };
};

export type SearchAgentByKeyWordResponse = RListAgentDTO;

export type SearchAgentByKeyWordError = RVoid;

export type GetAgentReleaseHistoryData = {
  query: {
    /**
     * Agent ID
     */
    agentId: string;
    /**
     * 页码
     */
    pageNum: number;
    /**
     * 每页数量
     */
    pageSize: number;
  };
};

export type GetAgentReleaseHistoryResponse = RPageResultAgentReleaseDTO;

export type GetAgentReleaseHistoryError = RVoid;

export type GetPublicAgentsData = {
  query: {
    /**
     * 分类
     */
    category?: string;
    /**
     * 当前页
     */
    pageNum: number;
    /**
     * 每页数量，最大100
     */
    pageSize: number;
    /**
     * 平台
     */
    platform?: string;
    /**
     * 查找内容
     */
    search?: string;
    /**
     * 排序
     */
    sort?: string;
    /**
     * 标签
     */
    tags?: Array<string>;
  };
};

export type GetPublicAgentsResponse = RPageResultAgentDTO;

export type GetPublicAgentsError = RVoid;

export type DownloadAgentMarkdownData = {
  path: {
    /**
     * Agent ID
     */
    id: string;
  };
};

export type DownloadAgentMarkdownResponse = Blob | File;

export type DownloadAgentMarkdownError = RVoid;

export type GetAgentForkUsersData = {
  query: {
    agentId: string;
    pageNum: number;
    pageSize: number;
  };
};

export type GetAgentForkUsersResponse = RPageResultUserDTO;

export type GetAgentForkUsersError = RVoid;

export type ListForkedAgentsData = {
  query: {
    originalAgentId: string;
    pageNum: number;
    pageSize: number;
  };
};

export type ListForkedAgentsResponse = RPageResultAgentDTO;

export type ListForkedAgentsError = RVoid;

export type CountForksData = {
  query: {
    agentId: string;
  };
};

export type CountForksResponse = RInteger;

export type CountForksError = RVoid;

export type ExportAgentData = {
  query: {
    /**
     * Agent ID
     */
    id: string;
  };
};

export type ExportAgentResponse = Blob | File;

export type ExportAgentError = RVoid;

export type GetAgentByUserNameAndAgentNameData = {
  query: {
    agentName: string;
    userName: string;
  };
};

export type GetAgentByUserNameAndAgentNameResponse = RAgentDTO;

export type GetAgentByUserNameAndAgentNameError = RVoid;

export type CleanCreationChatSessionResponse = RBoolean;

export type CleanCreationChatSessionError = RVoid;

export type DeleteFileData = {
  path: {
    /**
     * 文件ID
     */
    id: string;
  };
};

export type DeleteFileResponse = RBoolean;

export type DeleteFileError = RVoid;

export type DeleteFilesData = {
  body: Array<string>;
};

export type DeleteFilesResponse = RBoolean;

export type DeleteFilesError = RVoid;

export type DeleteAgentFileData = {
  query: {
    agentId: string;
    fileId: string;
  };
};

export type DeleteAgentFileResponse = RBoolean;

export type DeleteAgentFileError = RVoid;

export type $OpenApiTs = {
  '/api/v1/users/profile': {
    get: {
      res: {
        /**
         * OK
         */
        '200': RUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    put: {
      req: UpdateCurrentUserProfileData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/content': {
    put: {
      req: UpdateFileContentData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents': {
    get: {
      req: GetAgentByIdData;
      res: {
        /**
         * OK
         */
        '200': RAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    put: {
      req: UpdateAgentData;
      res: {
        /**
         * OK
         */
        '200': RObject;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    post: {
      req: CreateAgentData;
      res: {
        /**
         * OK
         */
        '200': RAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    delete: {
      req: DeleteAgentData;
      res: {
        /**
         * OK
         */
        '200': RObject;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/star': {
    get: {
      req: ListStarredAgentsData;
      res: {
        /**
         * OK
         */
        '200': RPageResultAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    put: {
      req: StarAgentData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    delete: {
      req: UnStarAgentData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/publish': {
    put: {
      req: PublishAgentData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/follow': {
    post: {
      req: FollowUserData;
      res: {
        /**
         * OK
         */
        '200': RObject;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
    delete: {
      req: UnfollowUserData;
      res: {
        /**
         * OK
         */
        '200': RObject;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/liteAgent/navigation': {
    post: {
      req: NavigationChatData;
      res: {
        /**
         * OK
         */
        '200': RNavigationResultDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/liteAgent/creation/chat': {
    post: {
      req: CreationChatData;
      res: {
        /**
         * OK
         */
        '200': Array<ServerSentEventAgentMessage>;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/tool': {
    post: {
      req: UploadToolFileData;
      res: {
        /**
         * OK
         */
        '200': RFileInfoDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/list': {
    post: {
      req: GetFileInfosByIdsData;
      res: {
        /**
         * OK
         */
        '200': RListFileInfoDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/knowledge': {
    post: {
      req: UploadKnowledgeFileData;
      res: {
        /**
         * OK
         */
        '200': RString;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/avatar': {
    post: {
      req: UploadAvatarFileData;
      res: {
        /**
         * OK
         */
        '200': RString;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/auth/signup': {
    post: {
      req: SignupData;
      res: {
        /**
         * OK
         */
        '200': RUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/auth/refresh': {
    post: {
      res: {
        /**
         * OK
         */
        '200': RObject;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/auth/logout': {
    post: {
      res: {
        /**
         * OK
         */
        '200': RObject;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/auth/login': {
    post: {
      req: LoginData;
      res: {
        /**
         * OK
         */
        '200': RSaTokenInfo;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/import': {
    post: {
      req: ImportAgentData;
      res: {
        /**
         * OK
         */
        '200': RAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/fork': {
    post: {
      req: ForkAgentData;
      res: {
        /**
         * OK
         */
        '200': RAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/verify-code': {
    post: {
      req: VerifyCodeData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/verify-captcha': {
    post: {
      req: VerifyCaptchaData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/send-registration-code': {
    post: {
      req: SendRegistrationCodeData;
      res: {
        /**
         * OK
         */
        '200': RVoid;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/send-phone-code': {
    post: {
      req: SendPhoneCodeData;
      res: {
        /**
         * OK
         */
        '200': RVoid;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/send-forget-password-code': {
    post: {
      req: SendForgetPasswordCodeData;
      res: {
        /**
         * OK
         */
        '200': RVoid;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/reset': {
    post: {
      req: ResetPasswordData;
      res: {
        /**
         * OK
         */
        '200': RVoid;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/change-password': {
    post: {
      req: ChangePasswordData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/account/captcha': {
    post: {
      res: {
        /**
         * OK
         */
        '200': unknown;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users': {
    get: {
      req: ListUsersData;
      res: {
        /**
         * OK
         */
        '200': RPageResultUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/stats': {
    get: {
      req: GetUserStatsData;
      res: {
        /**
         * OK
         */
        '200': RUserStatsDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/recent-actions': {
    get: {
      req: GetRecentUserActionsData;
      res: {
        /**
         * OK
         */
        '200': RListUserActionLogDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/profile-by-username': {
    get: {
      req: GetUserProfileByUsernameData;
      res: {
        /**
         * OK
         */
        '200': RUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/profile-by-id': {
    get: {
      req: GetUserProfileData;
      res: {
        /**
         * OK
         */
        '200': RUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/following': {
    get: {
      req: GetUserFollowingData;
      res: {
        /**
         * OK
         */
        '200': RPageResultUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/followers': {
    get: {
      req: GetUserFollowersData;
      res: {
        /**
         * OK
         */
        '200': RPageResultUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/users/actions': {
    get: {
      req: GetUserActionsData;
      res: {
        /**
         * OK
         */
        '200': RPageResultUserActionLogDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/knowledge/progress': {
    get: {
      req: UploadKnowledgeFile1Data;
      res: {
        /**
         * OK
         */
        '200': RConversionProgressDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/images/{imagesFileName}': {
    get: {
      req: GetImageFileData;
      res: {
        /**
         * OK
         */
        '200': Blob | File;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/content/{id}': {
    get: {
      req: GetFileContentData;
      res: {
        /**
         * OK
         */
        '200': Blob | File;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/user': {
    get: {
      req: GetUserAgentsData;
      res: {
        /**
         * OK
         */
        '200': RPageResultAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/trending': {
    get: {
      req: GetTrendingAgentsData;
      res: {
        /**
         * OK
         */
        '200': RPageResultAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/star/users': {
    get: {
      req: GetAgentStarUsersData;
      res: {
        /**
         * OK
         */
        '200': RPageResultUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/search-agent': {
    get: {
      req: SearchAgentByKeyWordData;
      res: {
        /**
         * OK
         */
        '200': RListAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/release/history': {
    get: {
      req: GetAgentReleaseHistoryData;
      res: {
        /**
         * OK
         */
        '200': RPageResultAgentReleaseDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/public': {
    get: {
      req: GetPublicAgentsData;
      res: {
        /**
         * OK
         */
        '200': RPageResultAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/md/{id}': {
    get: {
      req: DownloadAgentMarkdownData;
      res: {
        /**
         * OK
         */
        '200': Blob | File;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/fork/users': {
    get: {
      req: GetAgentForkUsersData;
      res: {
        /**
         * OK
         */
        '200': RPageResultUserDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/fork/list': {
    get: {
      req: ListForkedAgentsData;
      res: {
        /**
         * OK
         */
        '200': RPageResultAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/fork/count': {
    get: {
      req: CountForksData;
      res: {
        /**
         * OK
         */
        '200': RInteger;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/export': {
    get: {
      req: ExportAgentData;
      res: {
        /**
         * OK
         */
        '200': Blob | File;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/by-name': {
    get: {
      req: GetAgentByUserNameAndAgentNameData;
      res: {
        /**
         * OK
         */
        '200': RAgentDTO;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/liteAgent/creation/clean-session': {
    delete: {
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/{id}': {
    delete: {
      req: DeleteFileData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/file/batch': {
    delete: {
      req: DeleteFilesData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
  '/api/v1/agents/files': {
    delete: {
      req: DeleteAgentFileData;
      res: {
        /**
         * OK
         */
        '200': RBoolean;
        /**
         * Unauthorized
         */
        '401': RVoid;
        /**
         * Forbidden
         */
        '403': RVoid;
        /**
         * Internal Server Error
         */
        '500': RVoid;
      };
    };
  };
};

export type GetCurrentUserProfileResponseTransformer = (
  data: any
) => Promise<GetCurrentUserProfileResponse>;

export type RUserDTOModelResponseTransformer = (data: any) => RUserDTO;

export type UserDTOModelResponseTransformer = (data: any) => UserDTO;

export const UserDTOModelResponseTransformer: UserDTOModelResponseTransformer =
  (data) => {
    if (data?.createTime) {
      data.createTime = new Date(data.createTime);
    }
    if (data?.updateTime) {
      data.updateTime = new Date(data.updateTime);
    }
    if (data?.lastLoginTime) {
      data.lastLoginTime = new Date(data.lastLoginTime);
    }
    return data;
  };

export const RUserDTOModelResponseTransformer: RUserDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      UserDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const GetCurrentUserProfileResponseTransformer: GetCurrentUserProfileResponseTransformer =
  async (data) => {
    RUserDTOModelResponseTransformer(data);
    return data;
  };

export type GetAgentByIdResponseTransformer = (
  data: any
) => Promise<GetAgentByIdResponse>;

export type RAgentDTOModelResponseTransformer = (data: any) => RAgentDTO;

export type AgentDTOModelResponseTransformer = (data: any) => AgentDTO;

export type ForkDTOModelResponseTransformer = (data: any) => ForkDTO;

export const ForkDTOModelResponseTransformer: ForkDTOModelResponseTransformer =
  (data) => {
    if (data?.createTime) {
      data.createTime = new Date(data.createTime);
    }
    return data;
  };

export type AgentLicenseDTOModelResponseTransformer = (
  data: any
) => AgentLicenseDTO;

export const AgentLicenseDTOModelResponseTransformer: AgentLicenseDTOModelResponseTransformer =
  (data) => {
    if (data?.createTime) {
      data.createTime = new Date(data.createTime);
    }
    if (data?.updateTime) {
      data.updateTime = new Date(data.updateTime);
    }
    return data;
  };

export const AgentDTOModelResponseTransformer: AgentDTOModelResponseTransformer =
  (data) => {
    if (data?.createTime) {
      data.createTime = new Date(data.createTime);
    }
    if (data?.updateTime) {
      data.updateTime = new Date(data.updateTime);
    }
    if (data?.forkInfo) {
      ForkDTOModelResponseTransformer(data.forkInfo);
    }
    if (data?.license) {
      AgentLicenseDTOModelResponseTransformer(data.license);
    }
    return data;
  };

export const RAgentDTOModelResponseTransformer: RAgentDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      AgentDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const GetAgentByIdResponseTransformer: GetAgentByIdResponseTransformer =
  async (data) => {
    RAgentDTOModelResponseTransformer(data);
    return data;
  };

export type CreateAgentResponseTransformer = (
  data: any
) => Promise<CreateAgentResponse>;

export const CreateAgentResponseTransformer: CreateAgentResponseTransformer =
  async (data) => {
    RAgentDTOModelResponseTransformer(data);
    return data;
  };

export type ListStarredAgentsResponseTransformer = (
  data: any
) => Promise<ListStarredAgentsResponse>;

export type RPageResultAgentDTOModelResponseTransformer = (
  data: any
) => RPageResultAgentDTO;

export type PageResultAgentDTOModelResponseTransformer = (
  data: any
) => PageResultAgentDTO;

export const PageResultAgentDTOModelResponseTransformer: PageResultAgentDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.contentData)) {
      data.contentData.forEach(AgentDTOModelResponseTransformer);
    }
    return data;
  };

export const RPageResultAgentDTOModelResponseTransformer: RPageResultAgentDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      PageResultAgentDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const ListStarredAgentsResponseTransformer: ListStarredAgentsResponseTransformer =
  async (data) => {
    RPageResultAgentDTOModelResponseTransformer(data);
    return data;
  };

export type NavigationChatResponseTransformer = (
  data: any
) => Promise<NavigationChatResponse>;

export type RNavigationResultDTOModelResponseTransformer = (
  data: any
) => RNavigationResultDTO;

export type NavigationResultDTOModelResponseTransformer = (
  data: any
) => NavigationResultDTO;

export const NavigationResultDTOModelResponseTransformer: NavigationResultDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.agentDTOS)) {
      data.agentDTOS.forEach(AgentDTOModelResponseTransformer);
    }
    return data;
  };

export const RNavigationResultDTOModelResponseTransformer: RNavigationResultDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      NavigationResultDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const NavigationChatResponseTransformer: NavigationChatResponseTransformer =
  async (data) => {
    RNavigationResultDTOModelResponseTransformer(data);
    return data;
  };

export type UploadToolFileResponseTransformer = (
  data: any
) => Promise<UploadToolFileResponse>;

export type RFileInfoDTOModelResponseTransformer = (data: any) => RFileInfoDTO;

export type FileInfoDTOModelResponseTransformer = (data: any) => FileInfoDTO;

export const FileInfoDTOModelResponseTransformer: FileInfoDTOModelResponseTransformer =
  (data) => {
    if (data?.uploadTime) {
      data.uploadTime = new Date(data.uploadTime);
    }
    return data;
  };

export const RFileInfoDTOModelResponseTransformer: RFileInfoDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      FileInfoDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const UploadToolFileResponseTransformer: UploadToolFileResponseTransformer =
  async (data) => {
    RFileInfoDTOModelResponseTransformer(data);
    return data;
  };

export type GetFileInfosByIdsResponseTransformer = (
  data: any
) => Promise<GetFileInfosByIdsResponse>;

export type RListFileInfoDTOModelResponseTransformer = (
  data: any
) => RListFileInfoDTO;

export const RListFileInfoDTOModelResponseTransformer: RListFileInfoDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.data)) {
      data.data.forEach(FileInfoDTOModelResponseTransformer);
    }
    return data;
  };

export const GetFileInfosByIdsResponseTransformer: GetFileInfosByIdsResponseTransformer =
  async (data) => {
    RListFileInfoDTOModelResponseTransformer(data);
    return data;
  };

export type SignupResponseTransformer = (data: any) => Promise<SignupResponse>;

export const SignupResponseTransformer: SignupResponseTransformer = async (
  data
) => {
  RUserDTOModelResponseTransformer(data);
  return data;
};

export type ImportAgentResponseTransformer = (
  data: any
) => Promise<ImportAgentResponse>;

export const ImportAgentResponseTransformer: ImportAgentResponseTransformer =
  async (data) => {
    RAgentDTOModelResponseTransformer(data);
    return data;
  };

export type ForkAgentResponseTransformer = (
  data: any
) => Promise<ForkAgentResponse>;

export const ForkAgentResponseTransformer: ForkAgentResponseTransformer =
  async (data) => {
    RAgentDTOModelResponseTransformer(data);
    return data;
  };

export type ListUsersResponseTransformer = (
  data: any
) => Promise<ListUsersResponse>;

export type RPageResultUserDTOModelResponseTransformer = (
  data: any
) => RPageResultUserDTO;

export type PageResultUserDTOModelResponseTransformer = (
  data: any
) => PageResultUserDTO;

export const PageResultUserDTOModelResponseTransformer: PageResultUserDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.contentData)) {
      data.contentData.forEach(UserDTOModelResponseTransformer);
    }
    return data;
  };

export const RPageResultUserDTOModelResponseTransformer: RPageResultUserDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      PageResultUserDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const ListUsersResponseTransformer: ListUsersResponseTransformer =
  async (data) => {
    RPageResultUserDTOModelResponseTransformer(data);
    return data;
  };

export type GetRecentUserActionsResponseTransformer = (
  data: any
) => Promise<GetRecentUserActionsResponse>;

export type RListUserActionLogDTOModelResponseTransformer = (
  data: any
) => RListUserActionLogDTO;

export type UserActionLogDTOModelResponseTransformer = (
  data: any
) => UserActionLogDTO;

export const UserActionLogDTOModelResponseTransformer: UserActionLogDTOModelResponseTransformer =
  (data) => {
    if (data?.actionTime) {
      data.actionTime = new Date(data.actionTime);
    }
    return data;
  };

export const RListUserActionLogDTOModelResponseTransformer: RListUserActionLogDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.data)) {
      data.data.forEach(UserActionLogDTOModelResponseTransformer);
    }
    return data;
  };

export const GetRecentUserActionsResponseTransformer: GetRecentUserActionsResponseTransformer =
  async (data) => {
    RListUserActionLogDTOModelResponseTransformer(data);
    return data;
  };

export type GetUserProfileByUsernameResponseTransformer = (
  data: any
) => Promise<GetUserProfileByUsernameResponse>;

export const GetUserProfileByUsernameResponseTransformer: GetUserProfileByUsernameResponseTransformer =
  async (data) => {
    RUserDTOModelResponseTransformer(data);
    return data;
  };

export type GetUserProfileResponseTransformer = (
  data: any
) => Promise<GetUserProfileResponse>;

export const GetUserProfileResponseTransformer: GetUserProfileResponseTransformer =
  async (data) => {
    RUserDTOModelResponseTransformer(data);
    return data;
  };

export type GetUserFollowingResponseTransformer = (
  data: any
) => Promise<GetUserFollowingResponse>;

export const GetUserFollowingResponseTransformer: GetUserFollowingResponseTransformer =
  async (data) => {
    RPageResultUserDTOModelResponseTransformer(data);
    return data;
  };

export type GetUserFollowersResponseTransformer = (
  data: any
) => Promise<GetUserFollowersResponse>;

export const GetUserFollowersResponseTransformer: GetUserFollowersResponseTransformer =
  async (data) => {
    RPageResultUserDTOModelResponseTransformer(data);
    return data;
  };

export type GetUserActionsResponseTransformer = (
  data: any
) => Promise<GetUserActionsResponse>;

export type RPageResultUserActionLogDTOModelResponseTransformer = (
  data: any
) => RPageResultUserActionLogDTO;

export type PageResultUserActionLogDTOModelResponseTransformer = (
  data: any
) => PageResultUserActionLogDTO;

export const PageResultUserActionLogDTOModelResponseTransformer: PageResultUserActionLogDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.contentData)) {
      data.contentData.forEach(UserActionLogDTOModelResponseTransformer);
    }
    return data;
  };

export const RPageResultUserActionLogDTOModelResponseTransformer: RPageResultUserActionLogDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      PageResultUserActionLogDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const GetUserActionsResponseTransformer: GetUserActionsResponseTransformer =
  async (data) => {
    RPageResultUserActionLogDTOModelResponseTransformer(data);
    return data;
  };

export type UploadKnowledgeFile1ResponseTransformer = (
  data: any
) => Promise<UploadKnowledgeFile1Response>;

export type RConversionProgressDTOModelResponseTransformer = (
  data: any
) => RConversionProgressDTO;

export type ConversionProgressDTOModelResponseTransformer = (
  data: any
) => ConversionProgressDTO;

export const ConversionProgressDTOModelResponseTransformer: ConversionProgressDTOModelResponseTransformer =
  (data) => {
    if (data?.fileInfoDTO) {
      FileInfoDTOModelResponseTransformer(data.fileInfoDTO);
    }
    return data;
  };

export const RConversionProgressDTOModelResponseTransformer: RConversionProgressDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      ConversionProgressDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const UploadKnowledgeFile1ResponseTransformer: UploadKnowledgeFile1ResponseTransformer =
  async (data) => {
    RConversionProgressDTOModelResponseTransformer(data);
    return data;
  };

export type GetUserAgentsResponseTransformer = (
  data: any
) => Promise<GetUserAgentsResponse>;

export const GetUserAgentsResponseTransformer: GetUserAgentsResponseTransformer =
  async (data) => {
    RPageResultAgentDTOModelResponseTransformer(data);
    return data;
  };

export type GetTrendingAgentsResponseTransformer = (
  data: any
) => Promise<GetTrendingAgentsResponse>;

export const GetTrendingAgentsResponseTransformer: GetTrendingAgentsResponseTransformer =
  async (data) => {
    RPageResultAgentDTOModelResponseTransformer(data);
    return data;
  };

export type GetAgentStarUsersResponseTransformer = (
  data: any
) => Promise<GetAgentStarUsersResponse>;

export const GetAgentStarUsersResponseTransformer: GetAgentStarUsersResponseTransformer =
  async (data) => {
    RPageResultUserDTOModelResponseTransformer(data);
    return data;
  };

export type SearchAgentByKeyWordResponseTransformer = (
  data: any
) => Promise<SearchAgentByKeyWordResponse>;

export type RListAgentDTOModelResponseTransformer = (
  data: any
) => RListAgentDTO;

export const RListAgentDTOModelResponseTransformer: RListAgentDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.data)) {
      data.data.forEach(AgentDTOModelResponseTransformer);
    }
    return data;
  };

export const SearchAgentByKeyWordResponseTransformer: SearchAgentByKeyWordResponseTransformer =
  async (data) => {
    RListAgentDTOModelResponseTransformer(data);
    return data;
  };

export type GetAgentReleaseHistoryResponseTransformer = (
  data: any
) => Promise<GetAgentReleaseHistoryResponse>;

export type RPageResultAgentReleaseDTOModelResponseTransformer = (
  data: any
) => RPageResultAgentReleaseDTO;

export type PageResultAgentReleaseDTOModelResponseTransformer = (
  data: any
) => PageResultAgentReleaseDTO;

export type AgentReleaseDTOModelResponseTransformer = (
  data: any
) => AgentReleaseDTO;

export const AgentReleaseDTOModelResponseTransformer: AgentReleaseDTOModelResponseTransformer =
  (data) => {
    if (data?.createTime) {
      data.createTime = new Date(data.createTime);
    }
    return data;
  };

export const PageResultAgentReleaseDTOModelResponseTransformer: PageResultAgentReleaseDTOModelResponseTransformer =
  (data) => {
    if (Array.isArray(data?.contentData)) {
      data.contentData.forEach(AgentReleaseDTOModelResponseTransformer);
    }
    return data;
  };

export const RPageResultAgentReleaseDTOModelResponseTransformer: RPageResultAgentReleaseDTOModelResponseTransformer =
  (data) => {
    if (data?.data) {
      PageResultAgentReleaseDTOModelResponseTransformer(data.data);
    }
    return data;
  };

export const GetAgentReleaseHistoryResponseTransformer: GetAgentReleaseHistoryResponseTransformer =
  async (data) => {
    RPageResultAgentReleaseDTOModelResponseTransformer(data);
    return data;
  };

export type GetPublicAgentsResponseTransformer = (
  data: any
) => Promise<GetPublicAgentsResponse>;

export const GetPublicAgentsResponseTransformer: GetPublicAgentsResponseTransformer =
  async (data) => {
    RPageResultAgentDTOModelResponseTransformer(data);
    return data;
  };

export type GetAgentForkUsersResponseTransformer = (
  data: any
) => Promise<GetAgentForkUsersResponse>;

export const GetAgentForkUsersResponseTransformer: GetAgentForkUsersResponseTransformer =
  async (data) => {
    RPageResultUserDTOModelResponseTransformer(data);
    return data;
  };

export type ListForkedAgentsResponseTransformer = (
  data: any
) => Promise<ListForkedAgentsResponse>;

export const ListForkedAgentsResponseTransformer: ListForkedAgentsResponseTransformer =
  async (data) => {
    RPageResultAgentDTOModelResponseTransformer(data);
    return data;
  };

export type GetAgentByUserNameAndAgentNameResponseTransformer = (
  data: any
) => Promise<GetAgentByUserNameAndAgentNameResponse>;

export const GetAgentByUserNameAndAgentNameResponseTransformer: GetAgentByUserNameAndAgentNameResponseTransformer =
  async (data) => {
    RAgentDTOModelResponseTransformer(data);
    return data;
  };
